%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Autogenerated multilingual MCFG grammar
%% Optimized for parsing with the Active bottomup algorithm
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Start symbols for language module: user

%% No start symbols defined

%% Optimized clauses for language module: user

:- discontiguous eps_rule/3, tok_rule/5, cat_rule/7.

cat_rule('Bu', s0, 1, s0, [arg('Bu', 1, s1), arg('Bu', 1, s2)], [], rule('S', 'S', c('Bu'))).
cat_rule('As', s0, 1, s0, [], [s1=[arg('As', 2, s0)]], rule('At', 'At', c('As', 'As'))).
cat_rule('CA', s0, 1, s0, [arg('CA', 1, s1), arg('CA', 1, s2), arg('AE', 2, s0)], [s1=[arg('AE', 2, s1)], s2=[arg('AE', 2, s2)]], rule('AE', 'AE', c('CA', 'AE'))).
cat_rule('DG', s0, 1, s0, [], [s1=[arg('DG', 1, s1)], s2=[arg('DG', 1, s2), arg('Br', 2, s0), arg('Br', 2, s1), arg('Br', 2, s2)], s3=[arg('Br', 2, s3)]], rule('AF', 'AF', c('DG', 'Br'))).
cat_rule('Dl', s0, 1, s0, [], [s1=[arg('Dl', 1, s1)], s2=[arg('Dl', 1, s2), arg('CW', 2, s0), arg('CW', 2, s1), arg('CW', 2, s2)], s3=[arg('CW', 2, s3)]], rule('AF', 'AF', c('Dl', 'CW'))).
cat_rule('DG', s0, 1, s0, [], [s1=[arg('DG', 1, s1)], s2=[arg('DG', 1, s2), arg('Aa', 2, s0), arg('Aa', 2, s1), arg('Aa', 2, s2)], s3=[arg('Aa', 2, s3)], s4=[arg('Aa', 2, s4)]], rule('AG', 'AG', c('DG', 'Aa'))).
cat_rule('Dl', s0, 1, s0, [], [s1=[arg('Dl', 1, s1)], s2=[arg('Dl', 1, s2), arg('Al', 2, s0), arg('Al', 2, s1), arg('Al', 2, s2)], s3=[arg('Al', 2, s3)], s4=[arg('Al', 2, s4)]], rule('AG', 'AG', c('Dl', 'Al'))).
cat_rule('DG', s0, 1, s0, [], [s1=[arg('DG', 1, s1)], s2=[arg('DG', 1, s2), arg(r, 2, s0), arg(r, 2, s1), arg(r, 2, s2)], s3=[arg(r, 2, s3)], s4=[arg(r, 2, s4)], s5=[arg(r, 2, s5)]], rule('AH', 'AH', c('DG', r))).
cat_rule('Dl', s0, 1, s0, [], [s1=[arg('Dl', 1, s1)], s2=[arg('Dl', 1, s2), arg(y, 2, s0), arg(y, 2, s1), arg(y, 2, s2)], s3=[arg(y, 2, s3)], s4=[arg(y, 2, s4)], s5=[arg(y, 2, s5)]], rule('AH', 'AH', c('Dl', y))).
cat_rule('DG', s0, 1, s0, [], [s1=[arg('DG', 1, s1)], s2=[arg('DG', 1, s2), arg('Ab', 2, s0), arg('Ab', 2, s1), arg('Ab', 2, s2)], s3=[arg('Ab', 2, s3)], s4=[arg('Ab', 2, s4)]], rule('AI', 'AI', c('DG', 'Ab'))).
cat_rule('Dl', s0, 1, s0, [], [s1=[arg('Dl', 1, s1)], s2=[arg('Dl', 1, s2), arg('Am', 2, s0), arg('Am', 2, s1), arg('Am', 2, s2)], s3=[arg('Am', 2, s3)], s4=[arg('Am', 2, s4)]], rule('AI', 'AI', c('Dl', 'Am'))).
cat_rule('DG', s0, 1, s0, [], [s1=[arg('DG', 1, s1)], s2=[arg('DG', 1, s2), arg(s, 2, s0), arg(s, 2, s1), arg(s, 2, s2)], s3=[arg(s, 2, s3)], s4=[arg(s, 2, s4)], s5=[arg(s, 2, s5)]], rule('AJ', 'AJ', c('DG', s))).
cat_rule('Dl', s0, 1, s0, [], [s1=[arg('Dl', 1, s1)], s2=[arg('Dl', 1, s2), arg(z, 2, s0), arg(z, 2, s1), arg(z, 2, s2)], s3=[arg(z, 2, s3)], s4=[arg(z, 2, s4)], s5=[arg(z, 2, s5)]], rule('AJ', 'AJ', c('Dl', z))).
cat_rule('DG', s0, 1, s0, [], [s1=[arg('DG', 1, s1)], s2=[arg('DG', 1, s2), arg('Bs', 2, s0), arg('Bs', 2, s1), arg('Bs', 2, s2)], s3=[arg('Bs', 2, s3)]], rule('AK', 'AK', c('DG', 'Bs'))).
cat_rule('Dl', s0, 1, s0, [], [s1=[arg('Dl', 1, s1)], s2=[arg('Dl', 1, s2), arg('CX', 2, s0), arg('CX', 2, s1), arg('CX', 2, s2)], s3=[arg('CX', 2, s3)]], rule('AK', 'AK', c('Dl', 'CX'))).
cat_rule('DG', s0, 1, s0, [], [s1=[arg('DG', 1, s1)], s2=[arg('DG', 1, s2), arg('Bt', 2, s0), arg('Bt', 2, s1), arg('Bt', 2, s2)], s3=[arg('Bt', 2, s3)], s4=[arg('Bt', 2, s4)]], rule('AL', 'AL', c('DG', 'Bt'))).
cat_rule('Dl', s0, 1, s0, [], [s1=[arg('Dl', 1, s1)], s2=[arg('Dl', 1, s2), arg('CY', 2, s0), arg('CY', 2, s1), arg('CY', 2, s2)], s3=[arg('CY', 2, s3)], s4=[arg('CY', 2, s4)]], rule('AL', 'AL', c('Dl', 'CY'))).
cat_rule('Dm', s0, 1, s0, [], [s1=[arg('Dm', 1, s1)], s2=[arg('Dm', 1, s2), arg('CW', 2, s0), arg('CW', 2, s1), arg('CW', 2, s2)], s3=[arg('CW', 2, s3)]], rule('BX', 'BX', c('Dm', 'CW'))).
cat_rule('Dm', s0, 1, s0, [], [s1=[arg('Dm', 1, s1)], s2=[arg('Dm', 1, s2), arg('Al', 2, s0), arg('Al', 2, s1), arg('Al', 2, s2)], s3=[arg('Al', 2, s3)], s4=[arg('Al', 2, s4)]], rule('BY', 'BY', c('Dm', 'Al'))).
cat_rule('Dm', s0, 1, s0, [], [s1=[arg('Dm', 1, s1)], s2=[arg('Dm', 1, s2), arg(y, 2, s0), arg(y, 2, s1), arg(y, 2, s2)], s3=[arg(y, 2, s3)], s4=[arg(y, 2, s4)], s5=[arg(y, 2, s5)]], rule('BZ', 'BZ', c('Dm', y))).
cat_rule('Dm', s0, 1, s0, [], [s1=[arg('Dm', 1, s1)], s2=[arg('Dm', 1, s2), arg('Am', 2, s0), arg('Am', 2, s1), arg('Am', 2, s2)], s3=[arg('Am', 2, s3)], s4=[arg('Am', 2, s4)]], rule('Ba', 'Ba', c('Dm', 'Am'))).
cat_rule('Dm', s0, 1, s0, [], [s1=[arg('Dm', 1, s1)], s2=[arg('Dm', 1, s2), arg(z, 2, s0), arg(z, 2, s1), arg(z, 2, s2)], s3=[arg(z, 2, s3)], s4=[arg(z, 2, s4)], s5=[arg(z, 2, s5)]], rule('Bb', 'Bb', c('Dm', z))).
cat_rule('Dm', s0, 1, s0, [], [s1=[arg('Dm', 1, s1)], s2=[arg('Dm', 1, s2), arg('CX', 2, s0), arg('CX', 2, s1), arg('CX', 2, s2)], s3=[arg('CX', 2, s3)]], rule('Bc', 'Bc', c('Dm', 'CX'))).
cat_rule('Dm', s0, 1, s0, [], [s1=[arg('Dm', 1, s1)], s2=[arg('Dm', 1, s2), arg('CY', 2, s0), arg('CY', 2, s1), arg('CY', 2, s2)], s3=[arg('CY', 2, s3)], s4=[arg('CY', 2, s4)]], rule('Bd', 'Bd', c('Dm', 'CY'))).
cat_rule('Dh', s0, 1, s0, [], [s1=[arg('Dh', 1, s1)], s2=[arg('Dh', 1, s2), arg('CO', 2, s0), arg('CO', 2, s1), arg('CO', 2, s2)]], rule('Be', 'Be', c('Dh', 'CO'))).
cat_rule('Dh', s0, 1, s0, [], [s1=[arg('Dh', 1, s1)], s2=[arg('Dh', 1, s2), arg('CP', 2, s0), arg('CP', 2, s1), arg('CP', 2, s2)], s3=[arg('CP', 2, s3)]], rule('Bf', 'Bf', c('Dh', 'CP'))).
cat_rule('Dh', s0, 1, s0, [], [s1=[arg('Dh', 1, s1)], s2=[arg('Dh', 1, s2), arg('CQ', 2, s0), arg('CQ', 2, s1), arg('CQ', 2, s2)], s3=[arg('CQ', 2, s3)], s4=[arg('CQ', 2, s4)]], rule('Bg', 'Bg', c('Dh', 'CQ'))).
cat_rule('Dh', s0, 1, s0, [], [s1=[arg('Dh', 1, s1)], s2=[arg('Dh', 1, s2), arg('Ah', 2, s0), arg('Ah', 2, s1), arg('Ah', 2, s2)], s3=[arg('Ah', 2, s3)]], rule('Bh', 'Bh', c('Dh', 'Ah'))).
cat_rule('Dh', s0, 1, s0, [], [s1=[arg('Dh', 1, s1)], s2=[arg('Dh', 1, s2), arg('Ai', 2, s0), arg('Ai', 2, s1), arg('Ai', 2, s2)], s3=[arg('Ai', 2, s3)], s4=[arg('Ai', 2, s4)]], rule('Bi', 'Bi', c('Dh', 'Ai'))).
cat_rule('Cz', s0, 1, s0, [], [s1=[arg('Cz', 1, s1)], s2=[arg('Cz', 1, s2), arg('BX', 2, s0), arg('BX', 2, s1), arg('BX', 2, s2)], s3=[arg('BX', 2, s3)]], rule('AM', 'AM', c('Cz', 'BX'))).
cat_rule('Dk', s0, 1, s0, [], [s1=[arg('Dk', 1, s1)], s2=[arg('Dk', 1, s2), arg('CT', 2, s0), arg('CT', 2, s1), arg('CT', 2, s2)], s3=[arg('CT', 2, s3)]], rule('AM', 'AM', c('Dk', 'CT'))).
cat_rule('Cz', s0, 1, s0, [], [s1=[arg('Cz', 1, s1)], s2=[arg('Cz', 1, s2), arg('BY', 2, s0), arg('BY', 2, s1), arg('BY', 2, s2)], s3=[arg('BY', 2, s3)], s4=[arg('BY', 2, s4)]], rule('AN', 'AN', c('Cz', 'BY'))).
cat_rule('Dk', s0, 1, s0, [], [s1=[arg('Dk', 1, s1)], s2=[arg('Dk', 1, s2), arg('Aj', 2, s0), arg('Aj', 2, s1), arg('Aj', 2, s2)], s3=[arg('Aj', 2, s3)], s4=[arg('Aj', 2, s4)]], rule('AN', 'AN', c('Dk', 'Aj'))).
cat_rule('Cz', s0, 1, s0, [], [s1=[arg('Cz', 1, s1)], s2=[arg('Cz', 1, s2), arg('BZ', 2, s0), arg('BZ', 2, s1), arg('BZ', 2, s2)], s3=[arg('BZ', 2, s3)], s4=[arg('BZ', 2, s4)], s5=[arg('BZ', 2, s5)]], rule('AO', 'AO', c('Cz', 'BZ'))).
cat_rule('Dk', s0, 1, s0, [], [s1=[arg('Dk', 1, s1)], s2=[arg('Dk', 1, s2), arg(w, 2, s0), arg(w, 2, s1), arg(w, 2, s2)], s3=[arg(w, 2, s3)], s4=[arg(w, 2, s4)], s5=[arg(w, 2, s5)]], rule('AO', 'AO', c('Dk', w))).
cat_rule('Cz', s0, 1, s0, [], [s1=[arg('Cz', 1, s1)], s2=[arg('Cz', 1, s2), arg('Ba', 2, s0), arg('Ba', 2, s1), arg('Ba', 2, s2)], s3=[arg('Ba', 2, s3)], s4=[arg('Ba', 2, s4)]], rule('AP', 'AP', c('Cz', 'Ba'))).
cat_rule('Dk', s0, 1, s0, [], [s1=[arg('Dk', 1, s1)], s2=[arg('Dk', 1, s2), arg('Ak', 2, s0), arg('Ak', 2, s1), arg('Ak', 2, s2)], s3=[arg('Ak', 2, s3)], s4=[arg('Ak', 2, s4)]], rule('AP', 'AP', c('Dk', 'Ak'))).
cat_rule('Cz', s0, 1, s0, [], [s1=[arg('Cz', 1, s1)], s2=[arg('Cz', 1, s2), arg('Bb', 2, s0), arg('Bb', 2, s1), arg('Bb', 2, s2)], s3=[arg('Bb', 2, s3)], s4=[arg('Bb', 2, s4)], s5=[arg('Bb', 2, s5)]], rule('AQ', 'AQ', c('Cz', 'Bb'))).
cat_rule('Dk', s0, 1, s0, [], [s1=[arg('Dk', 1, s1)], s2=[arg('Dk', 1, s2), arg(x, 2, s0), arg(x, 2, s1), arg(x, 2, s2)], s3=[arg(x, 2, s3)], s4=[arg(x, 2, s4)], s5=[arg(x, 2, s5)]], rule('AQ', 'AQ', c('Dk', x))).
cat_rule('Cz', s0, 1, s0, [], [s1=[arg('Cz', 1, s1)], s2=[arg('Cz', 1, s2), arg('Bc', 2, s0), arg('Bc', 2, s1), arg('Bc', 2, s2)], s3=[arg('Bc', 2, s3)]], rule('AR', 'AR', c('Cz', 'Bc'))).
cat_rule('Dk', s0, 1, s0, [], [s1=[arg('Dk', 1, s1)], s2=[arg('Dk', 1, s2), arg('CU', 2, s0), arg('CU', 2, s1), arg('CU', 2, s2)], s3=[arg('CU', 2, s3)]], rule('AR', 'AR', c('Dk', 'CU'))).
cat_rule('Cz', s0, 1, s0, [], [s1=[arg('Cz', 1, s1)], s2=[arg('Cz', 1, s2), arg('Bd', 2, s0), arg('Bd', 2, s1), arg('Bd', 2, s2)], s3=[arg('Bd', 2, s3)], s4=[arg('Bd', 2, s4)]], rule('AT', 'AT', c('Cz', 'Bd'))).
cat_rule('Dk', s0, 1, s0, [], [s1=[arg('Dk', 1, s1)], s2=[arg('Dk', 1, s2), arg('CV', 2, s0), arg('CV', 2, s1), arg('CV', 2, s2)], s3=[arg('CV', 2, s3)], s4=[arg('CV', 2, s4)]], rule('AT', 'AT', c('Dk', 'CV'))).
cat_rule('Cy', s0, 1, s0, [], [s1=[arg('Cy', 1, s1)], s2=[arg('Cy', 1, s2), arg('AF', 2, s0), arg('AF', 2, s1), arg('AF', 2, s2)], s3=[arg('AF', 2, s3)]], rule(j, j, c('Cy', 'AF'))).
cat_rule('DC', s0, 1, s0, [], [s1=[arg('DC', 1, s1)], s2=[arg('DC', 1, s2), arg('AM', 2, s0), arg('AM', 2, s1), arg('AM', 2, s2)], s3=[arg('AM', 2, s3)]], rule(j, j, c('DC', 'AM'))).
cat_rule('Dc', s0, 1, s0, [], [s1=[arg('Dc', 1, s1)], s2=[arg('Dc', 1, s2), arg('CB', 2, s0), arg('CB', 2, s1), arg('CB', 2, s2)], s3=[arg('CB', 2, s3)]], rule(j, j, c('Dc', 'CB'))).
cat_rule('Cy', s0, 1, s0, [], [s1=[arg('Cy', 1, s1)], s2=[arg('Cy', 1, s2), arg('AG', 2, s0), arg('AG', 2, s1), arg('AG', 2, s2)], s3=[arg('AG', 2, s3)], s4=[arg('AG', 2, s4)]], rule(k, k, c('Cy', 'AG'))).
cat_rule('DC', s0, 1, s0, [], [s1=[arg('DC', 1, s1)], s2=[arg('DC', 1, s2), arg('AN', 2, s0), arg('AN', 2, s1), arg('AN', 2, s2)], s3=[arg('AN', 2, s3)], s4=[arg('AN', 2, s4)]], rule(k, k, c('DC', 'AN'))).
cat_rule('Dc', s0, 1, s0, [], [s1=[arg('Dc', 1, s1)], s2=[arg('Dc', 1, s2), arg('Ae', 2, s0), arg('Ae', 2, s1), arg('Ae', 2, s2)], s3=[arg('Ae', 2, s3)], s4=[arg('Ae', 2, s4)]], rule(k, k, c('Dc', 'Ae'))).
cat_rule('Cy', s0, 1, s0, [], [s1=[arg('Cy', 1, s1)], s2=[arg('Cy', 1, s2), arg('AH', 2, s0), arg('AH', 2, s1), arg('AH', 2, s2)], s3=[arg('AH', 2, s3)], s4=[arg('AH', 2, s4)], s5=[arg('AH', 2, s5)]], rule(l, l, c('Cy', 'AH'))).
cat_rule('DC', s0, 1, s0, [], [s1=[arg('DC', 1, s1)], s2=[arg('DC', 1, s2), arg('AO', 2, s0), arg('AO', 2, s1), arg('AO', 2, s2)], s3=[arg('AO', 2, s3)], s4=[arg('AO', 2, s4)], s5=[arg('AO', 2, s5)]], rule(l, l, c('DC', 'AO'))).
cat_rule('Dc', s0, 1, s0, [], [s1=[arg('Dc', 1, s1)], s2=[arg('Dc', 1, s2), arg(u, 2, s0), arg(u, 2, s1), arg(u, 2, s2)], s3=[arg(u, 2, s3)], s4=[arg(u, 2, s4)], s5=[arg(u, 2, s5)]], rule(l, l, c('Dc', u))).
cat_rule('Cy', s0, 1, s0, [], [s1=[arg('Cy', 1, s1)], s2=[arg('Cy', 1, s2), arg('AI', 2, s0), arg('AI', 2, s1), arg('AI', 2, s2)], s3=[arg('AI', 2, s3)], s4=[arg('AI', 2, s4)]], rule(m, m, c('Cy', 'AI'))).
cat_rule('DC', s0, 1, s0, [], [s1=[arg('DC', 1, s1)], s2=[arg('DC', 1, s2), arg('AP', 2, s0), arg('AP', 2, s1), arg('AP', 2, s2)], s3=[arg('AP', 2, s3)], s4=[arg('AP', 2, s4)]], rule(m, m, c('DC', 'AP'))).
cat_rule('Dc', s0, 1, s0, [], [s1=[arg('Dc', 1, s1)], s2=[arg('Dc', 1, s2), arg('Af', 2, s0), arg('Af', 2, s1), arg('Af', 2, s2)], s3=[arg('Af', 2, s3)], s4=[arg('Af', 2, s4)]], rule(m, m, c('Dc', 'Af'))).
cat_rule('Cy', s0, 1, s0, [], [s1=[arg('Cy', 1, s1)], s2=[arg('Cy', 1, s2), arg('AJ', 2, s0), arg('AJ', 2, s1), arg('AJ', 2, s2)], s3=[arg('AJ', 2, s3)], s4=[arg('AJ', 2, s4)], s5=[arg('AJ', 2, s5)]], rule(n, n, c('Cy', 'AJ'))).
cat_rule('DC', s0, 1, s0, [], [s1=[arg('DC', 1, s1)], s2=[arg('DC', 1, s2), arg('AQ', 2, s0), arg('AQ', 2, s1), arg('AQ', 2, s2)], s3=[arg('AQ', 2, s3)], s4=[arg('AQ', 2, s4)], s5=[arg('AQ', 2, s5)]], rule(n, n, c('DC', 'AQ'))).
cat_rule('Dc', s0, 1, s0, [], [s1=[arg('Dc', 1, s1)], s2=[arg('Dc', 1, s2), arg(v, 2, s0), arg(v, 2, s1), arg(v, 2, s2)], s3=[arg(v, 2, s3)], s4=[arg(v, 2, s4)], s5=[arg(v, 2, s5)]], rule(n, n, c('Dc', v))).
cat_rule('Cy', s0, 1, s0, [], [s1=[arg('Cy', 1, s1)], s2=[arg('Cy', 1, s2), arg('AK', 2, s0), arg('AK', 2, s1), arg('AK', 2, s2)], s3=[arg('AK', 2, s3)]], rule(o, o, c('Cy', 'AK'))).
cat_rule('DC', s0, 1, s0, [], [s1=[arg('DC', 1, s1)], s2=[arg('DC', 1, s2), arg('AR', 2, s0), arg('AR', 2, s1), arg('AR', 2, s2)], s3=[arg('AR', 2, s3)]], rule(o, o, c('DC', 'AR'))).
cat_rule('Dc', s0, 1, s0, [], [s1=[arg('Dc', 1, s1)], s2=[arg('Dc', 1, s2), arg('CC', 2, s0), arg('CC', 2, s1), arg('CC', 2, s2)], s3=[arg('CC', 2, s3)]], rule(o, o, c('Dc', 'CC'))).
cat_rule('Cy', s0, 1, s0, [], [s1=[arg('Cy', 1, s1)], s2=[arg('Cy', 1, s2), arg('AL', 2, s0), arg('AL', 2, s1), arg('AL', 2, s2)], s3=[arg('AL', 2, s3)], s4=[arg('AL', 2, s4)]], rule(p, p, c('Cy', 'AL'))).
cat_rule('DC', s0, 1, s0, [], [s1=[arg('DC', 1, s1)], s2=[arg('DC', 1, s2), arg('AT', 2, s0), arg('AT', 2, s1), arg('AT', 2, s2)], s3=[arg('AT', 2, s3)], s4=[arg('AT', 2, s4)]], rule(p, p, c('DC', 'AT'))).
cat_rule('Dc', s0, 1, s0, [], [s1=[arg('Dc', 1, s1)], s2=[arg('Dc', 1, s2), arg('CD', 2, s0), arg('CD', 2, s1), arg('CD', 2, s2)], s3=[arg('CD', 2, s3)], s4=[arg('CD', 2, s4)]], rule(p, p, c('Dc', 'CD'))).
cat_rule('De', s0, 1, s0, [], [s1=[arg('De', 1, s1)], s2=[arg('De', 1, s2), arg('W', 2, s0), arg('W', 2, s1), arg('W', 2, s2)]], rule('AU', 'AU', c('De', 'W'))).
cat_rule('Dn', s0, 1, s0, [], [s1=[arg('Dn', 1, s2)], s2=[arg('W', 2, s0), arg('W', 2, s1), arg('Dn', 1, s1), arg('W', 2, s2)]], rule('AU', 'AU', c('Dn', 'W'))).
cat_rule('De', s0, 1, s0, [], [s1=[arg('De', 1, s1)], s2=[arg('De', 1, s2), arg('X', 2, s0), arg('X', 2, s1), arg('X', 2, s2)], s3=[arg('X', 2, s3)]], rule(q, q, c('De', 'X'))).
cat_rule('De', s0, 1, s0, [], [s1=[arg('De', 1, s1)], s2=[arg('De', 1, s2)], s3=[arg('Ag', 2, s0), arg('Ag', 2, s1), arg('Ag', 2, s2)]], rule(q, q, c('De', 'Ag'))).
cat_rule('Dn', s0, 1, s0, [], [s1=[arg('Dn', 1, s2)], s2=[arg('X', 2, s0), arg('X', 2, s1), arg('Dn', 1, s1), arg('X', 2, s2)], s3=[arg('X', 2, s3)]], rule(q, q, c('Dn', 'X'))).
cat_rule('De', s0, 1, s0, [], [s1=[arg('De', 1, s1)], s2=[arg('De', 1, s2), arg('I', 2, s0), arg('I', 2, s1), arg('I', 2, s2)], s3=[arg('I', 2, s3)], s4=[arg('I', 2, s4)]], rule('AV', 'AV', c('De', 'I'))).
cat_rule('Dn', s0, 1, s0, [], [s1=[arg('Dn', 1, s2)], s2=[arg('I', 2, s0), arg('I', 2, s1), arg('Dn', 1, s1), arg('I', 2, s2)], s3=[arg('I', 2, s3)], s4=[arg('I', 2, s4)]], rule('AV', 'AV', c('Dn', 'I'))).
cat_rule('De', s0, 1, s0, [], [s1=[arg('De', 1, s1)], s2=[arg('De', 1, s2), arg('Y', 2, s0), arg('Y', 2, s1), arg('Y', 2, s2)], s3=[arg('Y', 2, s3)]], rule('AW', 'AW', c('De', 'Y'))).
cat_rule('Dn', s0, 1, s0, [], [s1=[arg('Dn', 1, s2)], s2=[arg('Y', 2, s0), arg('Y', 2, s1), arg('Dn', 1, s1), arg('Y', 2, s2)], s3=[arg('Y', 2, s3)]], rule('AW', 'AW', c('Dn', 'Y'))).
cat_rule('De', s0, 1, s0, [], [s1=[arg('De', 1, s1)], s2=[arg('De', 1, s2), arg('J', 2, s0), arg('J', 2, s1), arg('J', 2, s2)], s3=[arg('J', 2, s3)], s4=[arg('J', 2, s4)]], rule('AX', 'AX', c('De', 'J'))).
cat_rule('Dn', s0, 1, s0, [], [s1=[arg('Dn', 1, s2)], s2=[arg('J', 2, s0), arg('J', 2, s1), arg('Dn', 1, s1), arg('J', 2, s2)], s3=[arg('J', 2, s3)], s4=[arg('J', 2, s4)]], rule('AX', 'AX', c('Dn', 'J'))).
cat_rule('CZ', s3, 1, s0, [arg('CZ', 1, s0)], [s1=[arg('CZ', 1, s1)], s2=[arg('CZ', 1, s2)]], rule('Bj', 'Bj', c('CZ'))).
cat_rule('Ca', s3, 1, s0, [arg('Ca', 1, s0)], [s1=[arg('Ca', 1, s1)], s2=[arg('Ca', 1, s2)], s3=[arg('Ca', 1, s4)]], rule('Bk', 'Bk', c('Ca'))).
cat_rule('Cb', s3, 1, s0, [arg('Cb', 1, s0)], [s1=[arg('Cb', 1, s1)], s2=[arg('Cb', 1, s2)], s3=[arg('Cb', 1, s4)], s4=[arg('Cb', 1, s5)]], rule('Bl', 'Bl', c('Cb'))).
cat_rule('Cc', s3, 1, s0, [arg('Cc', 1, s0)], [s1=[arg('Cc', 1, s1)], s2=[arg('Cc', 1, s2)], s3=[arg('Cc', 1, s4)]], rule('AY', 'AY', c('Cc'))).
cat_rule('Ce', s0, 1, s0, [], [s1=[arg('Ce', 1, s1)], s2=[arg('Ce', 1, s2)], s3=[arg('Ce', 1, s3)]], rule('AY', 'AY', c('Ce'))).
cat_rule('Cd', s3, 1, s0, [arg('Cd', 1, s0)], [s1=[arg('Cd', 1, s1)], s2=[arg('Cd', 1, s2)], s3=[arg('Cd', 1, s4)], s4=[arg('Cd', 1, s5)]], rule('Bm', 'Bm', c('Cd'))).
cat_rule('Cf', s3, 1, s0, [arg('Cf', 1, s0)], [s1=[arg('Cf', 1, s1)], s2=[arg('Cf', 1, s2)]], rule('Bn', 'Bn', c('Cf'))).
cat_rule('Cg', s3, 1, s0, [arg('Cg', 1, s0)], [s1=[arg('Cg', 1, s1)], s2=[arg('Cg', 1, s2)], s3=[arg('Cg', 1, s4)]], rule('Bo', 'Bo', c('Cg'))).
cat_rule('Ch', s3, 1, s0, [arg('Ch', 1, s0)], [s1=[arg('Ch', 1, s1)], s2=[arg('Ch', 1, s2)], s3=[arg('Ch', 1, s4)], s4=[arg('Ch', 1, s5)]], rule('Bp', 'Bp', c('Ch'))).
cat_rule('Ci', s3, 1, s0, [arg('Ci', 1, s0)], [s1=[arg('Ci', 1, s1)], s2=[arg('Ci', 1, s2)], s3=[arg('Ci', 1, s4)]], rule('AZ', 'AZ', c('Ci'))).
cat_rule('Ck', s0, 1, s0, [], [s1=[arg('Ck', 1, s1)], s2=[arg('Ck', 1, s2)], s3=[arg('Ck', 1, s3)]], rule('AZ', 'AZ', c('Ck'))).
cat_rule('Cj', s3, 1, s0, [arg('Cj', 1, s0)], [s1=[arg('Cj', 1, s1)], s2=[arg('Cj', 1, s2)], s3=[arg('Cj', 1, s4)], s4=[arg('Cj', 1, s5)]], rule('Bq', 'Bq', c('Cj'))).
cat_rule('Ap', s0, 1, s0, [], [s1=[arg('Ap', 1, s1)], s2=[arg('Ap', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('Br', 'Br', c('Ap', t))).
cat_rule('Ap', s0, 1, s0, [], [s1=[arg('Ap', 1, s1)], s2=[arg('Ap', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('Aa', 'Aa', c('Ap', 'Ad'))).
cat_rule('EC', s0, 1, s0, [], [s1=[arg('EC', 1, s1)], s2=[arg('EC', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('EC', 1, s3)]], rule('Aa', 'Aa', c('EC', t))).
cat_rule('Ap', s0, 1, s0, [], [s1=[arg('Ap', 1, s1)], s2=[arg('Ap', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule(r, r, c('Ap', 'Bw'))).
cat_rule('EC', s0, 1, s0, [], [s1=[arg('EC', 1, s1)], s2=[arg('EC', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('EC', 1, s3)], s5=[arg('Bx', 2, s3)]], rule(r, r, c('EC', 'Bx'))).
cat_rule('ED', s0, 1, s0, [], [s1=[arg('ED', 1, s1)], s2=[arg('ED', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('ED', 1, s3)], s5=[arg('ED', 1, s4)]], rule(r, r, c('ED', t))).
cat_rule('Ap', s0, 1, s0, [], [s1=[arg('Ap', 1, s1)], s2=[arg('Ap', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('Ab', 'Ab', c('Ap', 'Bx'))).
cat_rule('Aq', s0, 1, s0, [], [s1=[arg('Aq', 1, s1)], s2=[arg('Aq', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('Aq', 1, s3)]], rule('Ab', 'Ab', c('Aq', t))).
cat_rule('Ap', s0, 1, s0, [], [s1=[arg('Ap', 1, s1)], s2=[arg('Ap', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule(s, s, c('Ap', 'By'))).
cat_rule('Aq', s0, 1, s0, [], [s1=[arg('Aq', 1, s1)], s2=[arg('Aq', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Aq', 1, s3)], s5=[arg('Ad', 2, s3)]], rule(s, s, c('Aq', 'Ad'))).
cat_rule('EE', s0, 1, s0, [], [s1=[arg('EE', 1, s1)], s2=[arg('EE', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('EE', 1, s3)], s5=[arg('EE', 1, s4)]], rule(s, s, c('EE', t))).
cat_rule('Ap', s0, 1, s0, [], [s1=[arg('Ap', 1, s1)], s2=[arg('Ap', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('Bs', 'Bs', c('Ap', 'Bz'))).
cat_rule('EC', s0, 1, s0, [], [s1=[arg('EC', 1, s1)], s2=[arg('EC', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)], s4=[arg('EC', 1, s3)]], rule('Bt', 'Bt', c('EC', 'Bz'))).
cat_rule('Di', s0, 1, s0, [], [s1=[arg('Di', 1, s1)], s2=[arg('Di', 1, s2), arg('CO', 2, s0), arg('CO', 2, s1), arg('CO', 2, s2)]], rule('Bu', 'Bu', c('Di', 'CO'))).
cat_rule('Cu', s3, 1, s0, [arg('Cu', 1, s0)], [s1=[arg('Cu', 1, s1)], s2=[arg('Cu', 1, s2)]], rule('Bv', 'Bv', c('Cu'))).
cat_rule('Ct', s4, 1, s0, [arg('Ct', 1, s0)], [s1=[arg('Ct', 1, s1)], s2=[arg('Ct', 1, s2)], s3=[arg('Ct', 1, s3)]], rule('Ac', 'Ac', c('Ct'))).
cat_rule('Cv', s3, 1, s0, [arg('Cv', 1, s0)], [s1=[arg('Cv', 1, s1)], s2=[arg('Cv', 1, s2)], s3=[arg('Cv', 1, s4)]], rule('Ac', 'Ac', c('Cv'))).
cat_rule('DD', s0, 1, s0, [], [s1=[arg('DD', 1, s1)], s2=[arg('DD', 1, s2), arg('AU', 2, s0), arg('AU', 2, s1), arg('AU', 2, s2)]], rule(t, t, c('DD', 'AU'))).
cat_rule('DH', s0, 1, s0, [], [s1=[arg('DH', 1, s1)], s2=[arg('DH', 1, s2), arg('Bv', 2, s0), arg('Bv', 2, s1), arg('Bv', 2, s2)]], rule(t, t, c('DH', 'Bv'))).
cat_rule('DD', s0, 1, s0, [], [s1=[arg('DD', 1, s1)], s2=[arg('DD', 1, s2), arg(q, 2, s0), arg(q, 2, s1), arg(q, 2, s2)], s3=[arg(q, 2, s3)]], rule('Ad', 'Ad', c('DD', q))).
cat_rule('DH', s0, 1, s0, [], [s1=[arg('DH', 1, s1)], s2=[arg('DH', 1, s2), arg('Ac', 2, s0), arg('Ac', 2, s1), arg('Ac', 2, s2)], s3=[arg('Ac', 2, s3)]], rule('Ad', 'Ad', c('DH', 'Ac'))).
cat_rule('DD', s0, 1, s0, [], [s1=[arg('DD', 1, s1)], s2=[arg('DD', 1, s2), arg('AV', 2, s0), arg('AV', 2, s1), arg('AV', 2, s2)], s3=[arg('AV', 2, s3)], s4=[arg('AV', 2, s4)]], rule('Bw', 'Bw', c('DD', 'AV'))).
cat_rule('DD', s0, 1, s0, [], [s1=[arg('DD', 1, s1)], s2=[arg('DD', 1, s2), arg('AW', 2, s0), arg('AW', 2, s1), arg('AW', 2, s2)], s3=[arg('AW', 2, s3)]], rule('Bx', 'Bx', c('DD', 'AW'))).
cat_rule('DD', s0, 1, s0, [], [s1=[arg('DD', 1, s1)], s2=[arg('DD', 1, s2), arg('AX', 2, s0), arg('AX', 2, s1), arg('AX', 2, s2)], s3=[arg('AX', 2, s3)], s4=[arg('AX', 2, s4)]], rule('By', 'By', c('DD', 'AX'))).
cat_rule('Cs', s3, 1, s0, [arg('Cs', 1, s0)], [s1=[arg('Cs', 1, s1)], s2=[arg('Cs', 1, s2)]], rule('Bz', 'Bz', c('Cs'))).
cat_rule('DI', s0, 1, s0, [], [s1=[arg('DI', 1, s1)], s2=[arg('DI', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('CB', 'CB', c('DI', t))).
cat_rule('DI', s0, 1, s0, [], [s1=[arg('DI', 1, s1)], s2=[arg('DI', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('Ae', 'Ae', c('DI', 'Ad'))).
cat_rule('DJ', s0, 1, s0, [], [s1=[arg('DJ', 1, s1)], s2=[arg('DJ', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DJ', 1, s3)]], rule('Ae', 'Ae', c('DJ', t))).
cat_rule('DI', s0, 1, s0, [], [s1=[arg('DI', 1, s1)], s2=[arg('DI', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule(u, u, c('DI', 'Bw'))).
cat_rule('DJ', s0, 1, s0, [], [s1=[arg('DJ', 1, s1)], s2=[arg('DJ', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('DJ', 1, s3)], s5=[arg('Bx', 2, s3)]], rule(u, u, c('DJ', 'Bx'))).
cat_rule('DK', s0, 1, s0, [], [s1=[arg('DK', 1, s1)], s2=[arg('DK', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DK', 1, s3)], s5=[arg('DK', 1, s4)]], rule(u, u, c('DK', t))).
cat_rule('DI', s0, 1, s0, [], [s1=[arg('DI', 1, s1)], s2=[arg('DI', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('Af', 'Af', c('DI', 'Bx'))).
cat_rule('DL', s0, 1, s0, [], [s1=[arg('DL', 1, s1)], s2=[arg('DL', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DL', 1, s3)]], rule('Af', 'Af', c('DL', t))).
cat_rule('DI', s0, 1, s0, [], [s1=[arg('DI', 1, s1)], s2=[arg('DI', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule(v, v, c('DI', 'By'))).
cat_rule('DL', s0, 1, s0, [], [s1=[arg('DL', 1, s1)], s2=[arg('DL', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('DL', 1, s3)], s5=[arg('Ad', 2, s3)]], rule(v, v, c('DL', 'Ad'))).
cat_rule('DM', s0, 1, s0, [], [s1=[arg('DM', 1, s1)], s2=[arg('DM', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DM', 1, s3)], s5=[arg('DM', 1, s4)]], rule(v, v, c('DM', t))).
cat_rule('DI', s0, 1, s0, [], [s1=[arg('DI', 1, s1)], s2=[arg('DI', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('CC', 'CC', c('DI', 'Bz'))).
cat_rule('DJ', s0, 1, s0, [], [s1=[arg('DJ', 1, s1)], s2=[arg('DJ', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)], s4=[arg('DJ', 1, s3)]], rule('CD', 'CD', c('DJ', 'Bz'))).
cat_rule('AE', s0, 1, s0, [arg('AE', 1, s1), arg('AE', 1, s2), arg('W', 2, s0)], [s1=[arg('W', 2, s1)], s2=[arg('W', 2, s2)]], rule('W', 'W', c('AE', 'W'))).
cat_rule('DA', s0, 1, s0, [], [s1=[arg('DA', 1, s1)], s2=[arg('DA', 1, s2), arg('Be', 2, s0), arg('Be', 2, s1), arg('Be', 2, s2)]], rule('W', 'W', c('DA', 'Be'))).
cat_rule('AU', s0, 2, s0, [arg('AU', 2, s1), arg('AU', 2, s2), arg('Dx', 1, s0)], [s1=[arg('Dx', 1, s1)], s2=[arg('Dx', 1, s2)]], rule('W', 'W', c('Dx', 'AU'))).
cat_rule('AE', s0, 1, s0, [arg('AE', 1, s1), arg('AE', 1, s2), arg('X', 2, s0)], [s1=[arg('X', 2, s1)], s2=[arg('X', 2, s2)], s3=[arg('X', 2, s3)]], rule('X', 'X', c('AE', 'X'))).
cat_rule('DA', s0, 1, s0, [], [s1=[arg('DA', 1, s1)], s2=[arg('DA', 1, s2), arg('Bf', 2, s0), arg('Bf', 2, s1), arg('Bf', 2, s2)], s3=[arg('Bf', 2, s3)]], rule('X', 'X', c('DA', 'Bf'))).
cat_rule(q, s0, 2, s0, [arg(q, 2, s1), arg(q, 2, s2), arg('Dx', 1, s0)], [s1=[arg('Dx', 1, s1)], s2=[arg('Dx', 1, s2)], s3=[arg(q, 2, s3)]], rule('X', 'X', c('Dx', q))).
cat_rule('AU', s0, 2, s0, [arg('AU', 2, s1), arg('AU', 2, s2), arg('Dy', 1, s0)], [s1=[arg('Dy', 1, s1)], s2=[arg('Dy', 1, s2)], s3=[arg('Dy', 1, s3)]], rule('X', 'X', c('Dy', 'AU'))).
cat_rule('AE', s0, 1, s0, [arg('AE', 1, s1), arg('AE', 1, s2), arg('I', 2, s0)], [s1=[arg('I', 2, s1)], s2=[arg('I', 2, s2)], s3=[arg('I', 2, s3)], s4=[arg('I', 2, s4)]], rule('I', 'I', c('AE', 'I'))).
cat_rule('DA', s0, 1, s0, [], [s1=[arg('DA', 1, s1)], s2=[arg('DA', 1, s2), arg('Bg', 2, s0), arg('Bg', 2, s1), arg('Bg', 2, s2)], s3=[arg('Bg', 2, s3)], s4=[arg('Bg', 2, s4)]], rule('I', 'I', c('DA', 'Bg'))).
cat_rule('AV', s0, 2, s0, [arg('AV', 2, s1), arg('AV', 2, s2), arg('Dx', 1, s0)], [s1=[arg('Dx', 1, s1)], s2=[arg('Dx', 1, s2)], s3=[arg('AV', 2, s3)], s4=[arg('AV', 2, s4)]], rule('I', 'I', c('Dx', 'AV'))).
cat_rule('AW', s0, 2, s0, [arg('AW', 2, s1), arg('AW', 2, s2), arg('Dy', 1, s0)], [s1=[arg('Dy', 1, s1)], s2=[arg('Dy', 1, s2)], s3=[arg('Dy', 1, s3)], s4=[arg('AW', 2, s3)]], rule('I', 'I', c('Dy', 'AW'))).
cat_rule('AU', s0, 2, s0, [arg('AU', 2, s1), arg('AU', 2, s2), arg('Dz', 1, s0)], [s1=[arg('Dz', 1, s1)], s2=[arg('Dz', 1, s2)], s3=[arg('Dz', 1, s3)], s4=[arg('Dz', 1, s4)]], rule('I', 'I', c('Dz', 'AU'))).
cat_rule('AE', s0, 1, s0, [arg('AE', 1, s1), arg('AE', 1, s2), arg('Y', 2, s0)], [s1=[arg('Y', 2, s1)], s2=[arg('Y', 2, s2)], s3=[arg('Y', 2, s3)]], rule('Y', 'Y', c('AE', 'Y'))).
cat_rule('DA', s0, 1, s0, [], [s1=[arg('DA', 1, s1)], s2=[arg('DA', 1, s2), arg('Bh', 2, s0), arg('Bh', 2, s1), arg('Bh', 2, s2)], s3=[arg('Bh', 2, s3)]], rule('Y', 'Y', c('DA', 'Bh'))).
cat_rule('AW', s0, 2, s0, [arg('AW', 2, s1), arg('AW', 2, s2), arg('Dx', 1, s0)], [s1=[arg('Dx', 1, s1)], s2=[arg('Dx', 1, s2)], s3=[arg('AW', 2, s3)]], rule('Y', 'Y', c('Dx', 'AW'))).
cat_rule('AU', s0, 2, s0, [arg('AU', 2, s1), arg('AU', 2, s2), arg('EA', 1, s0)], [s1=[arg('EA', 1, s1)], s2=[arg('EA', 1, s2)], s3=[arg('EA', 1, s3)]], rule('Y', 'Y', c('EA', 'AU'))).
cat_rule('AE', s0, 1, s0, [arg('AE', 1, s1), arg('AE', 1, s2), arg('J', 2, s0)], [s1=[arg('J', 2, s1)], s2=[arg('J', 2, s2)], s3=[arg('J', 2, s3)], s4=[arg('J', 2, s4)]], rule('J', 'J', c('AE', 'J'))).
cat_rule('DA', s0, 1, s0, [], [s1=[arg('DA', 1, s1)], s2=[arg('DA', 1, s2), arg('Bi', 2, s0), arg('Bi', 2, s1), arg('Bi', 2, s2)], s3=[arg('Bi', 2, s3)], s4=[arg('Bi', 2, s4)]], rule('J', 'J', c('DA', 'Bi'))).
cat_rule('AX', s0, 2, s0, [arg('AX', 2, s1), arg('AX', 2, s2), arg('Dx', 1, s0)], [s1=[arg('Dx', 1, s1)], s2=[arg('Dx', 1, s2)], s3=[arg('AX', 2, s3)], s4=[arg('AX', 2, s4)]], rule('J', 'J', c('Dx', 'AX'))).
cat_rule(q, s0, 2, s0, [arg(q, 2, s1), arg(q, 2, s2), arg('EA', 1, s0)], [s1=[arg('EA', 1, s1)], s2=[arg('EA', 1, s2)], s3=[arg('EA', 1, s3)], s4=[arg(q, 2, s3)]], rule('J', 'J', c('EA', q))).
cat_rule('AU', s0, 2, s0, [arg('AU', 2, s1), arg('AU', 2, s2), arg('EB', 1, s0)], [s1=[arg('EB', 1, s1)], s2=[arg('EB', 1, s2)], s3=[arg('EB', 1, s3)], s4=[arg('EB', 1, s4)]], rule('J', 'J', c('EB', 'AU'))).
cat_rule('AE', s0, 1, s0, [arg('AE', 1, s1), arg('AE', 1, s2), arg('Ag', 2, s0)], [s1=[arg('Ag', 2, s1)], s2=[arg('Ag', 2, s2)]], rule('Ag', 'Ag', c('AE', 'Ag'))).
cat_rule('Dr', s0, 1, s0, [], [s1=[arg('Bj', 2, s1), arg('Dr', 1, s1)], s2=[arg('Dr', 1, s2), arg('Bj', 2, s0), arg('Bj', 2, s2)]], rule('CE', 'CE', c('Dr', 'Bj'))).
cat_rule('Dr', s0, 1, s0, [], [s1=[arg('Bk', 2, s1), arg('Dr', 1, s1)], s2=[arg('Dr', 1, s2), arg('Bk', 2, s0), arg('Bk', 2, s2)], s3=[arg('Bk', 2, s3)]], rule('CF', 'CF', c('Dr', 'Bk'))).
cat_rule('Dr', s0, 1, s0, [], [s1=[arg('Bl', 2, s1), arg('Dr', 1, s1)], s2=[arg('Dr', 1, s2), arg('Bl', 2, s0), arg('Bl', 2, s2)], s3=[arg('Bl', 2, s3)], s4=[arg('Bl', 2, s4)]], rule('CG', 'CG', c('Dr', 'Bl'))).
cat_rule('Dr', s0, 1, s0, [], [s1=[arg('AY', 2, s1), arg('Dr', 1, s1)], s2=[arg('Dr', 1, s2), arg('AY', 2, s0), arg('AY', 2, s2)], s3=[arg('AY', 2, s3)]], rule('CH', 'CH', c('Dr', 'AY'))).
cat_rule('Dr', s0, 1, s0, [], [s1=[arg('Bm', 2, s1), arg('Dr', 1, s1)], s2=[arg('Dr', 1, s2), arg('Bm', 2, s0), arg('Bm', 2, s2)], s3=[arg('Bm', 2, s3)], s4=[arg('Bm', 2, s4)]], rule('CI', 'CI', c('Dr', 'Bm'))).
cat_rule('Ds', s0, 1, s0, [], [s1=[arg('Bn', 2, s1), arg('Ds', 1, s1)], s2=[arg('Ds', 1, s2), arg('Bn', 2, s0), arg('Bn', 2, s2)]], rule('CJ', 'CJ', c('Ds', 'Bn'))).
cat_rule('Ds', s0, 1, s0, [], [s1=[arg('Bo', 2, s1), arg('Ds', 1, s1)], s2=[arg('Ds', 1, s2), arg('Bo', 2, s0), arg('Bo', 2, s2)], s3=[arg('Bo', 2, s3)]], rule('CK', 'CK', c('Ds', 'Bo'))).
cat_rule('Ds', s0, 1, s0, [], [s1=[arg('Bp', 2, s1), arg('Ds', 1, s1)], s2=[arg('Ds', 1, s2), arg('Bp', 2, s0), arg('Bp', 2, s2)], s3=[arg('Bp', 2, s3)], s4=[arg('Bp', 2, s4)]], rule('CL', 'CL', c('Ds', 'Bp'))).
cat_rule('Ds', s0, 1, s0, [], [s1=[arg('AZ', 2, s1), arg('Ds', 1, s1)], s2=[arg('Ds', 1, s2), arg('AZ', 2, s0), arg('AZ', 2, s2)], s3=[arg('AZ', 2, s3)]], rule('CM', 'CM', c('Ds', 'AZ'))).
cat_rule('Ds', s0, 1, s0, [], [s1=[arg('Bq', 2, s1), arg('Ds', 1, s1)], s2=[arg('Ds', 1, s2), arg('Bq', 2, s0), arg('Bq', 2, s2)], s3=[arg('Bq', 2, s3)], s4=[arg('Bq', 2, s4)]], rule('CN', 'CN', c('Ds', 'Bq'))).
cat_rule('M', s3, 1, s0, [arg('M', 1, s0)], [s1=[arg('M', 1, s1)], s2=[arg('M', 1, s2)]], rule('CO', 'CO', c('M'))).
cat_rule('N', s3, 1, s0, [arg('N', 1, s0)], [s1=[arg('N', 1, s1)], s2=[arg('N', 1, s2)], s3=[arg('N', 1, s4)]], rule('CP', 'CP', c('N'))).
cat_rule('O', s3, 1, s0, [arg('O', 1, s0)], [s1=[arg('O', 1, s1)], s2=[arg('O', 1, s2)], s3=[arg('O', 1, s4)], s4=[arg('O', 1, s5)]], rule('CQ', 'CQ', c('O'))).
cat_rule('P', s3, 1, s0, [arg('P', 1, s0)], [s1=[arg('P', 1, s1)], s2=[arg('P', 1, s2)], s3=[arg('P', 1, s4)]], rule('Ah', 'Ah', c('P'))).
cat_rule('R', s0, 1, s0, [], [s1=[arg('R', 1, s1)], s2=[arg('R', 1, s2)], s3=[arg('R', 1, s3)]], rule('Ah', 'Ah', c('R'))).
cat_rule('Q', s3, 1, s0, [arg('Q', 1, s0)], [s1=[arg('Q', 1, s1)], s2=[arg('Q', 1, s2)], s3=[arg('Q', 1, s4)], s4=[arg('Q', 1, s5)]], rule('Ai', 'Ai', c('Q'))).
cat_rule('T', s0, 1, s0, [], [s1=[arg('T', 1, s1)], s2=[arg('T', 1, s2)], s3=[arg('T', 1, s3)], s4=[arg('T', 1, s4)]], rule('Ai', 'Ai', c('T'))).
cat_rule('H', s0, 2, s0, [], [s1=[arg('H', 2, s1)], s2=[arg('H', 2, s2), arg('CR', 1, s0), arg('CR', 1, s1), arg('CR', 1, s2)]], rule('H', 'H', c('CR', 'H'))).
cat_rule('An', s3, 1, s0, [arg('An', 1, s0)], [s1=[arg('An', 1, s1)], s2=[arg('An', 1, s2)]], rule('H', 'H', c('An'))).
cat_rule('Cw', s0, 1, s0, [], [s1=[arg('Cw', 1, s1)], s2=[arg('Cw', 1, s2), arg('AE', 2, s0), arg('AE', 2, s1), arg('AE', 2, s2)]], rule('H', 'H', c('Cw', 'AE'))).
cat_rule('DB', s0, 1, s0, [], [s1=[arg('DB', 1, s1)], s2=[arg('DB', 1, s2), arg('Be', 2, s0), arg('Be', 2, s1), arg('Be', 2, s2)]], rule('H', 'H', c('DB', 'Be'))).
cat_rule('Df', s0, 1, s0, [], [s1=[arg('Df', 1, s1)], s2=[arg('Df', 1, s2), arg('CE', 2, s0), arg('CE', 2, s1), arg('CE', 2, s2)]], rule('H', 'H', c('Df', 'CE'))).
cat_rule('Z', s0, 2, s0, [], [s1=[arg('Z', 2, s1)], s2=[arg('Z', 2, s2), arg('CR', 1, s0), arg('CR', 1, s1), arg('CR', 1, s2)], s3=[arg('Z', 2, s3)]], rule('Z', 'Z', c('CR', 'Z'))).
cat_rule('AA', s3, 1, s0, [arg('AA', 1, s0)], [s1=[arg('AA', 1, s1)], s2=[arg('AA', 1, s2)], s3=[arg('AA', 1, s4)]], rule('Z', 'Z', c('AA'))).
cat_rule('DB', s0, 1, s0, [], [s1=[arg('DB', 1, s1)], s2=[arg('DB', 1, s2), arg('Bf', 2, s0), arg('Bf', 2, s1), arg('Bf', 2, s2)], s3=[arg('Bf', 2, s3)]], rule('Z', 'Z', c('DB', 'Bf'))).
cat_rule('Df', s0, 1, s0, [], [s1=[arg('Df', 1, s1)], s2=[arg('Df', 1, s2), arg('CF', 2, s0), arg('CF', 2, s1), arg('CF', 2, s2)], s3=[arg('CF', 2, s3)]], rule('Z', 'Z', c('Df', 'CF'))).
cat_rule(a, s0, 2, s0, [], [s1=[arg(a, 2, s1)], s2=[arg(a, 2, s2), arg('CR', 1, s0), arg('CR', 1, s1), arg('CR', 1, s2)], s3=[arg(a, 2, s3)], s4=[arg(a, 2, s4)]], rule(a, a, c('CR', a))).
cat_rule(b, s3, 1, s0, [arg(b, 1, s0)], [s1=[arg(b, 1, s1)], s2=[arg(b, 1, s2)], s3=[arg(b, 1, s4)], s4=[arg(b, 1, s5)]], rule(a, a, c(b))).
cat_rule('DB', s0, 1, s0, [], [s1=[arg('DB', 1, s1)], s2=[arg('DB', 1, s2), arg('Bg', 2, s0), arg('Bg', 2, s1), arg('Bg', 2, s2)], s3=[arg('Bg', 2, s3)], s4=[arg('Bg', 2, s4)]], rule(a, a, c('DB', 'Bg'))).
cat_rule('Df', s0, 1, s0, [], [s1=[arg('Df', 1, s1)], s2=[arg('Df', 1, s2), arg('CG', 2, s0), arg('CG', 2, s1), arg('CG', 2, s2)], s3=[arg('CG', 2, s3)], s4=[arg('CG', 2, s4)]], rule(a, a, c('Df', 'CG'))).
cat_rule('K', s0, 2, s0, [], [s1=[arg('K', 2, s1)], s2=[arg('K', 2, s2), arg('CR', 1, s0), arg('CR', 1, s1), arg('CR', 1, s2)], s3=[arg('K', 2, s3)]], rule('K', 'K', c('CR', 'K'))).
cat_rule('AB', s3, 1, s0, [arg('AB', 1, s0)], [s1=[arg('AB', 1, s1)], s2=[arg('AB', 1, s2)], s3=[arg('AB', 1, s4)]], rule('K', 'K', c('AB'))).
cat_rule('Ao', s0, 1, s0, [], [s1=[arg('Ao', 1, s1)], s2=[arg('Ao', 1, s2)], s3=[arg('Ao', 1, s3)]], rule('K', 'K', c('Ao'))).
cat_rule('DB', s0, 1, s0, [], [s1=[arg('DB', 1, s1)], s2=[arg('DB', 1, s2), arg('Bh', 2, s0), arg('Bh', 2, s1), arg('Bh', 2, s2)], s3=[arg('Bh', 2, s3)]], rule('K', 'K', c('DB', 'Bh'))).
cat_rule('Df', s0, 1, s0, [], [s1=[arg('Df', 1, s1)], s2=[arg('Df', 1, s2), arg('CH', 2, s0), arg('CH', 2, s1), arg('CH', 2, s2)], s3=[arg('CH', 2, s3)]], rule('K', 'K', c('Df', 'CH'))).
cat_rule('L', s0, 2, s0, [], [s1=[arg('L', 2, s1)], s2=[arg('L', 2, s2), arg('CR', 1, s0), arg('CR', 1, s1), arg('CR', 1, s2)], s3=[arg('L', 2, s3)], s4=[arg('L', 2, s4)]], rule('L', 'L', c('CR', 'L'))).
cat_rule(c, s3, 1, s0, [arg(c, 1, s0)], [s1=[arg(c, 1, s1)], s2=[arg(c, 1, s2)], s3=[arg(c, 1, s4)], s4=[arg(c, 1, s5)]], rule('L', 'L', c(c))).
cat_rule('Cl', s0, 1, s0, [], [s1=[arg('Cl', 1, s1)], s2=[arg('Cl', 1, s2)], s3=[arg('Cl', 1, s3)], s4=[arg('Cl', 1, s4)]], rule('L', 'L', c('Cl'))).
cat_rule('DB', s0, 1, s0, [], [s1=[arg('DB', 1, s1)], s2=[arg('DB', 1, s2), arg('Bi', 2, s0), arg('Bi', 2, s1), arg('Bi', 2, s2)], s3=[arg('Bi', 2, s3)], s4=[arg('Bi', 2, s4)]], rule('L', 'L', c('DB', 'Bi'))).
cat_rule('Df', s0, 1, s0, [], [s1=[arg('Df', 1, s1)], s2=[arg('Df', 1, s2), arg('CI', 2, s0), arg('CI', 2, s1), arg('CI', 2, s2)], s3=[arg('CI', 2, s3)], s4=[arg('CI', 2, s4)]], rule('L', 'L', c('Df', 'CI'))).
cat_rule('DN', s0, 1, s0, [], [s1=[arg('DN', 1, s1)], s2=[arg('DN', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('CT', 'CT', c('DN', t))).
cat_rule('DN', s0, 1, s0, [], [s1=[arg('DN', 1, s1)], s2=[arg('DN', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('Aj', 'Aj', c('DN', 'Ad'))).
cat_rule('DO', s0, 1, s0, [], [s1=[arg('DO', 1, s1)], s2=[arg('DO', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DO', 1, s3)]], rule('Aj', 'Aj', c('DO', t))).
cat_rule('DN', s0, 1, s0, [], [s1=[arg('DN', 1, s1)], s2=[arg('DN', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule(w, w, c('DN', 'Bw'))).
cat_rule('DO', s0, 1, s0, [], [s1=[arg('DO', 1, s1)], s2=[arg('DO', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('DO', 1, s3)], s5=[arg('Bx', 2, s3)]], rule(w, w, c('DO', 'Bx'))).
cat_rule('DP', s0, 1, s0, [], [s1=[arg('DP', 1, s1)], s2=[arg('DP', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DP', 1, s3)], s5=[arg('DP', 1, s4)]], rule(w, w, c('DP', t))).
cat_rule('DN', s0, 1, s0, [], [s1=[arg('DN', 1, s1)], s2=[arg('DN', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('Ak', 'Ak', c('DN', 'Bx'))).
cat_rule('DQ', s0, 1, s0, [], [s1=[arg('DQ', 1, s1)], s2=[arg('DQ', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DQ', 1, s3)]], rule('Ak', 'Ak', c('DQ', t))).
cat_rule('DN', s0, 1, s0, [], [s1=[arg('DN', 1, s1)], s2=[arg('DN', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule(x, x, c('DN', 'By'))).
cat_rule('DQ', s0, 1, s0, [], [s1=[arg('DQ', 1, s1)], s2=[arg('DQ', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('DQ', 1, s3)], s5=[arg('Ad', 2, s3)]], rule(x, x, c('DQ', 'Ad'))).
cat_rule('DR', s0, 1, s0, [], [s1=[arg('DR', 1, s1)], s2=[arg('DR', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DR', 1, s3)], s5=[arg('DR', 1, s4)]], rule(x, x, c('DR', t))).
cat_rule('DN', s0, 1, s0, [], [s1=[arg('DN', 1, s1)], s2=[arg('DN', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('CU', 'CU', c('DN', 'Bz'))).
cat_rule('DO', s0, 1, s0, [], [s1=[arg('DO', 1, s1)], s2=[arg('DO', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)], s4=[arg('DO', 1, s3)]], rule('CV', 'CV', c('DO', 'Bz'))).
cat_rule('DT', s0, 1, s0, [], [s1=[arg('DT', 1, s1)], s2=[arg('DT', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('CW', 'CW', c('DT', t))).
cat_rule('DT', s0, 1, s0, [], [s1=[arg('DT', 1, s1)], s2=[arg('DT', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('Al', 'Al', c('DT', 'Ad'))).
cat_rule('DU', s0, 1, s0, [], [s1=[arg('DU', 1, s1)], s2=[arg('DU', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DU', 1, s3)]], rule('Al', 'Al', c('DU', t))).
cat_rule('DT', s0, 1, s0, [], [s1=[arg('DT', 1, s1)], s2=[arg('DT', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule(y, y, c('DT', 'Bw'))).
cat_rule('DU', s0, 1, s0, [], [s1=[arg('DU', 1, s1)], s2=[arg('DU', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('DU', 1, s3)], s5=[arg('Bx', 2, s3)]], rule(y, y, c('DU', 'Bx'))).
cat_rule('DV', s0, 1, s0, [], [s1=[arg('DV', 1, s1)], s2=[arg('DV', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DV', 1, s3)], s5=[arg('DV', 1, s4)]], rule(y, y, c('DV', t))).
cat_rule('DT', s0, 1, s0, [], [s1=[arg('DT', 1, s1)], s2=[arg('DT', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('Am', 'Am', c('DT', 'Bx'))).
cat_rule('DW', s0, 1, s0, [], [s1=[arg('DW', 1, s1)], s2=[arg('DW', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DW', 1, s3)]], rule('Am', 'Am', c('DW', t))).
cat_rule('DT', s0, 1, s0, [], [s1=[arg('DT', 1, s1)], s2=[arg('DT', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule(z, z, c('DT', 'By'))).
cat_rule('DW', s0, 1, s0, [], [s1=[arg('DW', 1, s1)], s2=[arg('DW', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('DW', 1, s3)], s5=[arg('Ad', 2, s3)]], rule(z, z, c('DW', 'Ad'))).
cat_rule('DX', s0, 1, s0, [], [s1=[arg('DX', 1, s1)], s2=[arg('DX', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('DX', 1, s3)], s5=[arg('DX', 1, s4)]], rule(z, z, c('DX', t))).
cat_rule('DT', s0, 1, s0, [], [s1=[arg('DT', 1, s1)], s2=[arg('DT', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('CX', 'CX', c('DT', 'Bz'))).
cat_rule('DU', s0, 1, s0, [], [s1=[arg('DU', 1, s1)], s2=[arg('DU', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)], s4=[arg('DU', 1, s3)]], rule('CY', 'CY', c('DU', 'Bz'))).
cat_rule('DY', s0, 1, s0, [], [s1=[arg('DY', 1, s1)], s2=[arg('DY', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('CZ', 'CZ', c('DY', t))).
cat_rule('DY', s0, 1, s0, [], [s1=[arg('DY', 1, s1)], s2=[arg('DY', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('Ca', 'Ca', c('DY', 'Ad'))).
cat_rule('DY', s0, 1, s0, [], [s1=[arg('DY', 1, s1)], s2=[arg('DY', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule('Cb', 'Cb', c('DY', 'Bw'))).
cat_rule('DY', s0, 1, s0, [], [s1=[arg('DY', 1, s1)], s2=[arg('DY', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('Cc', 'Cc', c('DY', 'Bx'))).
cat_rule('DY', s0, 1, s0, [], [s1=[arg('DY', 1, s1)], s2=[arg('DY', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule('Cd', 'Cd', c('DY', 'By'))).
cat_rule('DY', s0, 1, s0, [], [s1=[arg('DY', 1, s1)], s2=[arg('DY', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('Ce', 'Ce', c('DY', 'Bz'))).
cat_rule('DZ', s0, 1, s0, [], [s1=[arg('DZ', 1, s1)], s2=[arg('DZ', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('Cf', 'Cf', c('DZ', t))).
cat_rule('DZ', s0, 1, s0, [], [s1=[arg('DZ', 1, s1)], s2=[arg('DZ', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('Cg', 'Cg', c('DZ', 'Ad'))).
cat_rule('DZ', s0, 1, s0, [], [s1=[arg('DZ', 1, s1)], s2=[arg('DZ', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule('Ch', 'Ch', c('DZ', 'Bw'))).
cat_rule('DZ', s0, 1, s0, [], [s1=[arg('DZ', 1, s1)], s2=[arg('DZ', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('Ci', 'Ci', c('DZ', 'Bx'))).
cat_rule('DZ', s0, 1, s0, [], [s1=[arg('DZ', 1, s1)], s2=[arg('DZ', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule('Cj', 'Cj', c('DZ', 'By'))).
cat_rule('DZ', s0, 1, s0, [], [s1=[arg('DZ', 1, s1)], s2=[arg('DZ', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('Ck', 'Ck', c('DZ', 'Bz'))).
cat_rule('Dd', s0, 1, s0, [], [s1=[arg('Dd', 1, s1)], s2=[arg('Dd', 1, s2), arg('CB', 2, s0), arg('CB', 2, s1), arg('CB', 2, s2)], s3=[arg('CB', 2, s3)]], rule('M', 'M', c('Dd', 'CB'))).
cat_rule('Do', s0, 1, s0, [], [s1=[arg('AF', 2, s1), arg('Do', 1, s1)], s2=[arg('Do', 1, s2), arg('AF', 2, s0), arg('AF', 2, s2)], s3=[arg('AF', 2, s3)]], rule('M', 'M', c('Do', 'AF'))).
cat_rule('Dp', s0, 1, s0, [], [s1=[arg('AM', 2, s1), arg('Dp', 1, s1)], s2=[arg('Dp', 1, s2), arg('AM', 2, s0), arg('AM', 2, s2)], s3=[arg('AM', 2, s3)]], rule('M', 'M', c('Dp', 'AM'))).
cat_rule('Dq', s0, 1, s0, [], [s1=[arg(j, 2, s1), arg('Dq', 1, s1)], s2=[arg('Dq', 1, s2), arg(j, 2, s0), arg(j, 2, s2)], s3=[arg(j, 2, s3)]], rule('M', 'M', c('Dq', j))).
cat_rule('Dt', s0, 1, s0, [], [s1=[arg('CB', 2, s1), arg('Dt', 1, s1)], s2=[arg('Dt', 1, s2), arg('CB', 2, s0), arg('CB', 2, s2)], s3=[arg('CB', 2, s3)]], rule('M', 'M', c('Dt', 'CB'))).
cat_rule('Dd', s0, 1, s0, [], [s1=[arg('Dd', 1, s1)], s2=[arg('Dd', 1, s2), arg('Ae', 2, s0), arg('Ae', 2, s1), arg('Ae', 2, s2)], s3=[arg('Ae', 2, s3)], s4=[arg('Ae', 2, s4)]], rule('N', 'N', c('Dd', 'Ae'))).
cat_rule('Do', s0, 1, s0, [], [s1=[arg('AG', 2, s1), arg('Do', 1, s1)], s2=[arg('Do', 1, s2), arg('AG', 2, s0), arg('AG', 2, s2)], s3=[arg('AG', 2, s3)], s4=[arg('AG', 2, s4)]], rule('N', 'N', c('Do', 'AG'))).
cat_rule('Dp', s0, 1, s0, [], [s1=[arg('AN', 2, s1), arg('Dp', 1, s1)], s2=[arg('Dp', 1, s2), arg('AN', 2, s0), arg('AN', 2, s2)], s3=[arg('AN', 2, s3)], s4=[arg('AN', 2, s4)]], rule('N', 'N', c('Dp', 'AN'))).
cat_rule('Dq', s0, 1, s0, [], [s1=[arg(k, 2, s1), arg('Dq', 1, s1)], s2=[arg('Dq', 1, s2), arg(k, 2, s0), arg(k, 2, s2)], s3=[arg(k, 2, s3)], s4=[arg(k, 2, s4)]], rule('N', 'N', c('Dq', k))).
cat_rule('Dt', s0, 1, s0, [], [s1=[arg('Ae', 2, s1), arg('Dt', 1, s1)], s2=[arg('Dt', 1, s2), arg('Ae', 2, s0), arg('Ae', 2, s2)], s3=[arg('Ae', 2, s3)], s4=[arg('Ae', 2, s4)]], rule('N', 'N', c('Dt', 'Ae'))).
cat_rule('Dd', s0, 1, s0, [], [s1=[arg('Dd', 1, s1)], s2=[arg('Dd', 1, s2), arg(u, 2, s0), arg(u, 2, s1), arg(u, 2, s2)], s3=[arg(u, 2, s3)], s4=[arg(u, 2, s4)], s5=[arg(u, 2, s5)]], rule('O', 'O', c('Dd', u))).
cat_rule('Do', s0, 1, s0, [], [s1=[arg('AH', 2, s1), arg('Do', 1, s1)], s2=[arg('Do', 1, s2), arg('AH', 2, s0), arg('AH', 2, s2)], s3=[arg('AH', 2, s3)], s4=[arg('AH', 2, s4)], s5=[arg('AH', 2, s5)]], rule('O', 'O', c('Do', 'AH'))).
cat_rule('Dp', s0, 1, s0, [], [s1=[arg('AO', 2, s1), arg('Dp', 1, s1)], s2=[arg('Dp', 1, s2), arg('AO', 2, s0), arg('AO', 2, s2)], s3=[arg('AO', 2, s3)], s4=[arg('AO', 2, s4)], s5=[arg('AO', 2, s5)]], rule('O', 'O', c('Dp', 'AO'))).
cat_rule('Dq', s0, 1, s0, [], [s1=[arg(l, 2, s1), arg('Dq', 1, s1)], s2=[arg('Dq', 1, s2), arg(l, 2, s0), arg(l, 2, s2)], s3=[arg(l, 2, s3)], s4=[arg(l, 2, s4)], s5=[arg(l, 2, s5)]], rule('O', 'O', c('Dq', l))).
cat_rule('Dt', s0, 1, s0, [], [s1=[arg(u, 2, s1), arg('Dt', 1, s1)], s2=[arg('Dt', 1, s2), arg(u, 2, s0), arg(u, 2, s2)], s3=[arg(u, 2, s3)], s4=[arg(u, 2, s4)], s5=[arg(u, 2, s5)]], rule('O', 'O', c('Dt', u))).
cat_rule('Dd', s0, 1, s0, [], [s1=[arg('Dd', 1, s1)], s2=[arg('Dd', 1, s2), arg('Af', 2, s0), arg('Af', 2, s1), arg('Af', 2, s2)], s3=[arg('Af', 2, s3)], s4=[arg('Af', 2, s4)]], rule('P', 'P', c('Dd', 'Af'))).
cat_rule('Do', s0, 1, s0, [], [s1=[arg('AI', 2, s1), arg('Do', 1, s1)], s2=[arg('Do', 1, s2), arg('AI', 2, s0), arg('AI', 2, s2)], s3=[arg('AI', 2, s3)], s4=[arg('AI', 2, s4)]], rule('P', 'P', c('Do', 'AI'))).
cat_rule('Dp', s0, 1, s0, [], [s1=[arg('AP', 2, s1), arg('Dp', 1, s1)], s2=[arg('Dp', 1, s2), arg('AP', 2, s0), arg('AP', 2, s2)], s3=[arg('AP', 2, s3)], s4=[arg('AP', 2, s4)]], rule('P', 'P', c('Dp', 'AP'))).
cat_rule('Dq', s0, 1, s0, [], [s1=[arg(m, 2, s1), arg('Dq', 1, s1)], s2=[arg('Dq', 1, s2), arg(m, 2, s0), arg(m, 2, s2)], s3=[arg(m, 2, s3)], s4=[arg(m, 2, s4)]], rule('P', 'P', c('Dq', m))).
cat_rule('Dt', s0, 1, s0, [], [s1=[arg('Af', 2, s1), arg('Dt', 1, s1)], s2=[arg('Dt', 1, s2), arg('Af', 2, s0), arg('Af', 2, s2)], s3=[arg('Af', 2, s3)], s4=[arg('Af', 2, s4)]], rule('P', 'P', c('Dt', 'Af'))).
cat_rule('Dd', s0, 1, s0, [], [s1=[arg('Dd', 1, s1)], s2=[arg('Dd', 1, s2), arg(v, 2, s0), arg(v, 2, s1), arg(v, 2, s2)], s3=[arg(v, 2, s3)], s4=[arg(v, 2, s4)], s5=[arg(v, 2, s5)]], rule('Q', 'Q', c('Dd', v))).
cat_rule('Do', s0, 1, s0, [], [s1=[arg('AJ', 2, s1), arg('Do', 1, s1)], s2=[arg('Do', 1, s2), arg('AJ', 2, s0), arg('AJ', 2, s2)], s3=[arg('AJ', 2, s3)], s4=[arg('AJ', 2, s4)], s5=[arg('AJ', 2, s5)]], rule('Q', 'Q', c('Do', 'AJ'))).
cat_rule('Dp', s0, 1, s0, [], [s1=[arg('AQ', 2, s1), arg('Dp', 1, s1)], s2=[arg('Dp', 1, s2), arg('AQ', 2, s0), arg('AQ', 2, s2)], s3=[arg('AQ', 2, s3)], s4=[arg('AQ', 2, s4)], s5=[arg('AQ', 2, s5)]], rule('Q', 'Q', c('Dp', 'AQ'))).
cat_rule('Dq', s0, 1, s0, [], [s1=[arg(n, 2, s1), arg('Dq', 1, s1)], s2=[arg('Dq', 1, s2), arg(n, 2, s0), arg(n, 2, s2)], s3=[arg(n, 2, s3)], s4=[arg(n, 2, s4)], s5=[arg(n, 2, s5)]], rule('Q', 'Q', c('Dq', n))).
cat_rule('Dt', s0, 1, s0, [], [s1=[arg(v, 2, s1), arg('Dt', 1, s1)], s2=[arg('Dt', 1, s2), arg(v, 2, s0), arg(v, 2, s2)], s3=[arg(v, 2, s3)], s4=[arg(v, 2, s4)], s5=[arg(v, 2, s5)]], rule('Q', 'Q', c('Dt', v))).
cat_rule('Dd', s0, 1, s0, [], [s1=[arg('Dd', 1, s1)], s2=[arg('Dd', 1, s2), arg('CC', 2, s0), arg('CC', 2, s1), arg('CC', 2, s2)], s3=[arg('CC', 2, s3)]], rule('R', 'R', c('Dd', 'CC'))).
cat_rule('Do', s0, 1, s0, [], [s1=[arg('AK', 2, s1), arg('Do', 1, s1)], s2=[arg('Do', 1, s2), arg('AK', 2, s0), arg('AK', 2, s2)], s3=[arg('AK', 2, s3)]], rule('R', 'R', c('Do', 'AK'))).
cat_rule('Dp', s0, 1, s0, [], [s1=[arg('AR', 2, s1), arg('Dp', 1, s1)], s2=[arg('Dp', 1, s2), arg('AR', 2, s0), arg('AR', 2, s2)], s3=[arg('AR', 2, s3)]], rule('R', 'R', c('Dp', 'AR'))).
cat_rule('Dq', s0, 1, s0, [], [s1=[arg(o, 2, s1), arg('Dq', 1, s1)], s2=[arg('Dq', 1, s2), arg(o, 2, s0), arg(o, 2, s2)], s3=[arg(o, 2, s3)]], rule('R', 'R', c('Dq', o))).
cat_rule('Dt', s0, 1, s0, [], [s1=[arg('CC', 2, s1), arg('Dt', 1, s1)], s2=[arg('Dt', 1, s2), arg('CC', 2, s0), arg('CC', 2, s2)], s3=[arg('CC', 2, s3)]], rule('R', 'R', c('Dt', 'CC'))).
cat_rule('Dd', s0, 1, s0, [], [s1=[arg('Dd', 1, s1)], s2=[arg('Dd', 1, s2), arg('CD', 2, s0), arg('CD', 2, s1), arg('CD', 2, s2)], s3=[arg('CD', 2, s3)], s4=[arg('CD', 2, s4)]], rule('T', 'T', c('Dd', 'CD'))).
cat_rule('Do', s0, 1, s0, [], [s1=[arg('AL', 2, s1), arg('Do', 1, s1)], s2=[arg('Do', 1, s2), arg('AL', 2, s0), arg('AL', 2, s2)], s3=[arg('AL', 2, s3)], s4=[arg('AL', 2, s4)]], rule('T', 'T', c('Do', 'AL'))).
cat_rule('Dp', s0, 1, s0, [], [s1=[arg('AT', 2, s1), arg('Dp', 1, s1)], s2=[arg('Dp', 1, s2), arg('AT', 2, s0), arg('AT', 2, s2)], s3=[arg('AT', 2, s3)], s4=[arg('AT', 2, s4)]], rule('T', 'T', c('Dp', 'AT'))).
cat_rule('Dq', s0, 1, s0, [], [s1=[arg(p, 2, s1), arg('Dq', 1, s1)], s2=[arg('Dq', 1, s2), arg(p, 2, s0), arg(p, 2, s2)], s3=[arg(p, 2, s3)], s4=[arg(p, 2, s4)]], rule('T', 'T', c('Dq', p))).
cat_rule('Dt', s0, 1, s0, [], [s1=[arg('CD', 2, s1), arg('Dt', 1, s1)], s2=[arg('Dt', 1, s2), arg('CD', 2, s0), arg('CD', 2, s2)], s3=[arg('CD', 2, s3)], s4=[arg('CD', 2, s4)]], rule('T', 'T', c('Dt', 'CD'))).
cat_rule('Da', s0, 1, s0, [], [s1=[arg('Da', 1, s1)], s2=[arg('Da', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('An', 'An', c('Da', t))).
cat_rule('EF', s0, 1, s0, [], [s1=[arg('EF', 1, s1)], s2=[arg('EF', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('An', 'An', c('EF', t))).
cat_rule('Da', s0, 1, s0, [], [s1=[arg('Da', 1, s1)], s2=[arg('Da', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('AA', 'AA', c('Da', 'Ad'))).
cat_rule('EF', s0, 1, s0, [], [s1=[arg('EF', 1, s1)], s2=[arg('EF', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('AA', 'AA', c('EF', 'Ad'))).
cat_rule('EG', s0, 1, s0, [], [s1=[arg('EG', 1, s1)], s2=[arg('EG', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('EG', 1, s3)]], rule('AA', 'AA', c('EG', t))).
cat_rule('Da', s0, 1, s0, [], [s1=[arg('Da', 1, s1)], s2=[arg('Da', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule(b, b, c('Da', 'Bw'))).
cat_rule('EF', s0, 1, s0, [], [s1=[arg('EF', 1, s1)], s2=[arg('EF', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule(b, b, c('EF', 'Bw'))).
cat_rule('EG', s0, 1, s0, [], [s1=[arg('EG', 1, s1)], s2=[arg('EG', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('EG', 1, s3)], s5=[arg('Bx', 2, s3)]], rule(b, b, c('EG', 'Bx'))).
cat_rule('EH', s0, 1, s0, [], [s1=[arg('EH', 1, s1)], s2=[arg('EH', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('EH', 1, s3)], s5=[arg('EH', 1, s4)]], rule(b, b, c('EH', t))).
cat_rule('Da', s0, 1, s0, [], [s1=[arg('Da', 1, s1)], s2=[arg('Da', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('AB', 'AB', c('Da', 'Bx'))).
cat_rule('EF', s0, 1, s0, [], [s1=[arg('EF', 1, s1)], s2=[arg('EF', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('AB', 'AB', c('EF', 'Bx'))).
cat_rule('EI', s0, 1, s0, [], [s1=[arg('EI', 1, s1)], s2=[arg('EI', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('EI', 1, s3)]], rule('AB', 'AB', c('EI', t))).
cat_rule('Da', s0, 1, s0, [], [s1=[arg('Da', 1, s1)], s2=[arg('Da', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule(c, c, c('Da', 'By'))).
cat_rule('EF', s0, 1, s0, [], [s1=[arg('EF', 1, s1)], s2=[arg('EF', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule(c, c, c('EF', 'By'))).
cat_rule('EI', s0, 1, s0, [], [s1=[arg('EI', 1, s1)], s2=[arg('EI', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('EI', 1, s3)], s5=[arg('Ad', 2, s3)]], rule(c, c, c('EI', 'Ad'))).
cat_rule('EJ', s0, 1, s0, [], [s1=[arg('EJ', 1, s1)], s2=[arg('EJ', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)], s4=[arg('EJ', 1, s3)], s5=[arg('EJ', 1, s4)]], rule(c, c, c('EJ', t))).
cat_rule('Da', s0, 1, s0, [], [s1=[arg('Da', 1, s1)], s2=[arg('Da', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('Ao', 'Ao', c('Da', 'Bz'))).
cat_rule('EF', s0, 1, s0, [], [s1=[arg('EF', 1, s1)], s2=[arg('EF', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('Ao', 'Ao', c('EF', 'Bz'))).
cat_rule('EG', s0, 1, s0, [], [s1=[arg('EG', 1, s1)], s2=[arg('EG', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)], s4=[arg('EG', 1, s3)]], rule('Cl', 'Cl', c('EG', 'Bz'))).
cat_rule('Db', s0, 1, s0, [], [s1=[arg('Db', 1, s1)], s2=[arg('Db', 1, s2)], s3=[arg(t, 2, s0), arg(t, 2, s1), arg(t, 2, s2)]], rule('Cm', 'Cm', c('Db', t))).
cat_rule('Db', s0, 1, s0, [], [s1=[arg('Db', 1, s1)], s2=[arg('Db', 1, s2)], s3=[arg('Ad', 2, s0), arg('Ad', 2, s1), arg('Ad', 2, s2)], s4=[arg('Ad', 2, s3)]], rule('Cn', 'Cn', c('Db', 'Ad'))).
cat_rule('Db', s0, 1, s0, [], [s1=[arg('Db', 1, s1)], s2=[arg('Db', 1, s2)], s3=[arg('Bw', 2, s0), arg('Bw', 2, s1), arg('Bw', 2, s2)], s4=[arg('Bw', 2, s3)], s5=[arg('Bw', 2, s4)]], rule('Co', 'Co', c('Db', 'Bw'))).
cat_rule('Db', s0, 1, s0, [], [s1=[arg('Db', 1, s1)], s2=[arg('Db', 1, s2)], s3=[arg('Bx', 2, s0), arg('Bx', 2, s1), arg('Bx', 2, s2)], s4=[arg('Bx', 2, s3)]], rule('Cp', 'Cp', c('Db', 'Bx'))).
cat_rule('Db', s0, 1, s0, [], [s1=[arg('Db', 1, s1)], s2=[arg('Db', 1, s2)], s3=[arg('By', 2, s0), arg('By', 2, s1), arg('By', 2, s2)], s4=[arg('By', 2, s3)], s5=[arg('By', 2, s4)]], rule('Cq', 'Cq', c('Db', 'By'))).
cat_rule('Db', s0, 1, s0, [], [s1=[arg('Db', 1, s1)], s2=[arg('Db', 1, s2)], s3=[arg('Bz', 2, s0), arg('Bz', 2, s1), arg('Bz', 2, s2)]], rule('Cr', 'Cr', c('Db', 'Bz'))).
cat_rule('DE', s0, 1, s0, [], [s1=[arg('DE', 1, s1)], s2=[arg('DE', 1, s2), arg(q, 2, s0), arg(q, 2, s1), arg(q, 2, s2)], s3=[arg(q, 2, s3)]], rule('Cs', 'Cs', c('DE', q))).
cat_rule('Dj', s0, 1, s0, [], [s1=[arg('Dj', 1, s1)], s2=[arg('Dj', 1, s2), arg('CQ', 2, s0), arg('CQ', 2, s1), arg('CQ', 2, s2)], s3=[arg('CQ', 2, s3)], s4=[arg('CQ', 2, s4)]], rule('Ct', 'Ct', c('Dj', 'CQ'))).
cat_rule('Dj', s0, 1, s0, [], [s1=[arg('Dj', 1, s1)], s2=[arg('Dj', 1, s2), arg('Ah', 2, s0), arg('Ah', 2, s1), arg('Ah', 2, s2)], s3=[arg('Ah', 2, s3)]], rule('Cu', 'Cu', c('Dj', 'Ah'))).
cat_rule('Dj', s0, 1, s0, [], [s1=[arg('Dj', 1, s1)], s2=[arg('Dj', 1, s2), arg('Ai', 2, s0), arg('Ai', 2, s1), arg('Ai', 2, s2)], s3=[arg('Ai', 2, s3)], s4=[arg('Ai', 2, s4)]], rule('Cv', 'Cv', c('Dj', 'Ai'))).
cat_rule('Du', s0, 1, s0, [], [s1=[arg('H', 2, s1), arg('Du', 1, s1)], s2=[arg('Du', 1, s2), arg('H', 2, s0), arg('H', 2, s2)]], rule('DI', 'DI', c('Du', 'H'))).
cat_rule('Du', s0, 1, s0, [], [s1=[arg('Z', 2, s1), arg('Du', 1, s1)], s2=[arg('Du', 1, s2), arg('Z', 2, s0), arg('Z', 2, s2)], s3=[arg('Z', 2, s3)]], rule('DJ', 'DJ', c('Du', 'Z'))).
cat_rule('Du', s0, 1, s0, [], [s1=[arg(a, 2, s1), arg('Du', 1, s1)], s2=[arg('Du', 1, s2), arg(a, 2, s0), arg(a, 2, s2)], s3=[arg(a, 2, s3)], s4=[arg(a, 2, s4)]], rule('DK', 'DK', c('Du', a))).
cat_rule('Du', s0, 1, s0, [], [s1=[arg('K', 2, s1), arg('Du', 1, s1)], s2=[arg('Du', 1, s2), arg('K', 2, s0), arg('K', 2, s2)], s3=[arg('K', 2, s3)]], rule('DL', 'DL', c('Du', 'K'))).
cat_rule('Du', s0, 1, s0, [], [s1=[arg('L', 2, s1), arg('Du', 1, s1)], s2=[arg('Du', 1, s2), arg('L', 2, s0), arg('L', 2, s2)], s3=[arg('L', 2, s3)], s4=[arg('L', 2, s4)]], rule('DM', 'DM', c('Du', 'L'))).
cat_rule('Dv', s0, 1, s0, [], [s1=[arg('H', 2, s1), arg('Dv', 1, s1)], s2=[arg('Dv', 1, s2), arg('H', 2, s0), arg('H', 2, s2)]], rule('DN', 'DN', c('Dv', 'H'))).
cat_rule('Dv', s0, 1, s0, [], [s1=[arg('Z', 2, s1), arg('Dv', 1, s1)], s2=[arg('Dv', 1, s2), arg('Z', 2, s0), arg('Z', 2, s2)], s3=[arg('Z', 2, s3)]], rule('DO', 'DO', c('Dv', 'Z'))).
cat_rule('Dv', s0, 1, s0, [], [s1=[arg(a, 2, s1), arg('Dv', 1, s1)], s2=[arg('Dv', 1, s2), arg(a, 2, s0), arg(a, 2, s2)], s3=[arg(a, 2, s3)], s4=[arg(a, 2, s4)]], rule('DP', 'DP', c('Dv', a))).
cat_rule('Dv', s0, 1, s0, [], [s1=[arg('K', 2, s1), arg('Dv', 1, s1)], s2=[arg('Dv', 1, s2), arg('K', 2, s0), arg('K', 2, s2)], s3=[arg('K', 2, s3)]], rule('DQ', 'DQ', c('Dv', 'K'))).
cat_rule('Dv', s0, 1, s0, [], [s1=[arg('L', 2, s1), arg('Dv', 1, s1)], s2=[arg('Dv', 1, s2), arg('L', 2, s0), arg('L', 2, s2)], s3=[arg('L', 2, s3)], s4=[arg('L', 2, s4)]], rule('DR', 'DR', c('Dv', 'L'))).
cat_rule('Dw', s0, 1, s0, [], [s1=[arg('H', 2, s1), arg('Dw', 1, s1)], s2=[arg('Dw', 1, s2), arg('H', 2, s0), arg('H', 2, s2)]], rule('DT', 'DT', c('Dw', 'H'))).
cat_rule('Dw', s0, 1, s0, [], [s1=[arg('Z', 2, s1), arg('Dw', 1, s1)], s2=[arg('Dw', 1, s2), arg('Z', 2, s0), arg('Z', 2, s2)], s3=[arg('Z', 2, s3)]], rule('DU', 'DU', c('Dw', 'Z'))).
cat_rule('Dw', s0, 1, s0, [], [s1=[arg(a, 2, s1), arg('Dw', 1, s1)], s2=[arg('Dw', 1, s2), arg(a, 2, s0), arg(a, 2, s2)], s3=[arg(a, 2, s3)], s4=[arg(a, 2, s4)]], rule('DV', 'DV', c('Dw', a))).
cat_rule('Dw', s0, 1, s0, [], [s1=[arg('K', 2, s1), arg('Dw', 1, s1)], s2=[arg('Dw', 1, s2), arg('K', 2, s0), arg('K', 2, s2)], s3=[arg('K', 2, s3)]], rule('DW', 'DW', c('Dw', 'K'))).
cat_rule('Dw', s0, 1, s0, [], [s1=[arg('L', 2, s1), arg('Dw', 1, s1)], s2=[arg('Dw', 1, s2), arg('L', 2, s0), arg('L', 2, s2)], s3=[arg('L', 2, s3)], s4=[arg('L', 2, s4)]], rule('DX', 'DX', c('Dw', 'L'))).
cat_rule('DF', s0, 1, s0, [], [s1=[arg('DF', 1, s1)], s2=[arg('DF', 1, s2), arg('AU', 2, s0), arg('AU', 2, s1), arg('AU', 2, s2)]], rule('Dx', 'Dx', c('DF', 'AU'))).
cat_rule('DF', s0, 1, s0, [], [s1=[arg('DF', 1, s1)], s2=[arg('DF', 1, s2), arg(q, 2, s0), arg(q, 2, s1), arg(q, 2, s2)], s3=[arg(q, 2, s3)]], rule('Dy', 'Dy', c('DF', q))).
cat_rule('DF', s0, 1, s0, [], [s1=[arg('DF', 1, s1)], s2=[arg('DF', 1, s2), arg('AV', 2, s0), arg('AV', 2, s1), arg('AV', 2, s2)], s3=[arg('AV', 2, s3)], s4=[arg('AV', 2, s4)]], rule('Dz', 'Dz', c('DF', 'AV'))).
cat_rule('DF', s0, 1, s0, [], [s1=[arg('DF', 1, s1)], s2=[arg('DF', 1, s2), arg('AW', 2, s0), arg('AW', 2, s1), arg('AW', 2, s2)], s3=[arg('AW', 2, s3)]], rule('EA', 'EA', c('DF', 'AW'))).
cat_rule('DF', s0, 1, s0, [], [s1=[arg('DF', 1, s1)], s2=[arg('DF', 1, s2), arg('AX', 2, s0), arg('AX', 2, s1), arg('AX', 2, s2)], s3=[arg('AX', 2, s3)], s4=[arg('AX', 2, s4)]], rule('EB', 'EB', c('DF', 'AX'))).
cat_rule('Cm', s3, 1, s0, [arg('Cm', 1, s0)], [s1=[arg('Cm', 1, s1)], s2=[arg('Cm', 1, s2)]], rule('Ap', 'Ap', c('Cm'))).
cat_rule('Cx', s0, 1, s0, [], [s1=[arg('Cx', 1, s1)], s2=[arg('Cx', 1, s2), arg('AE', 2, s0), arg('AE', 2, s1), arg('AE', 2, s2)]], rule('Ap', 'Ap', c('Cx', 'AE'))).
cat_rule('Cn', s3, 1, s0, [arg('Cn', 1, s0)], [s1=[arg('Cn', 1, s1)], s2=[arg('Cn', 1, s2)], s3=[arg('Cn', 1, s4)]], rule('EC', 'EC', c('Cn'))).
cat_rule('Co', s3, 1, s0, [arg('Co', 1, s0)], [s1=[arg('Co', 1, s1)], s2=[arg('Co', 1, s2)], s3=[arg('Co', 1, s4)], s4=[arg('Co', 1, s5)]], rule('ED', 'ED', c('Co'))).
cat_rule('Cp', s3, 1, s0, [arg('Cp', 1, s0)], [s1=[arg('Cp', 1, s1)], s2=[arg('Cp', 1, s2)], s3=[arg('Cp', 1, s4)]], rule('Aq', 'Aq', c('Cp'))).
cat_rule('Cr', s0, 1, s0, [], [s1=[arg('Cr', 1, s1)], s2=[arg('Cr', 1, s2)], s3=[arg('Cr', 1, s3)]], rule('Aq', 'Aq', c('Cr'))).
cat_rule('Cq', s3, 1, s0, [arg('Cq', 1, s0)], [s1=[arg('Cq', 1, s1)], s2=[arg('Cq', 1, s2)], s3=[arg('Cq', 1, s4)], s4=[arg('Cq', 1, s5)]], rule('EE', 'EE', c('Cq'))).
cat_rule('Dg', s0, 1, s0, [], [s1=[arg('Dg', 1, s1)], s2=[arg('Dg', 1, s2), arg('CJ', 2, s0), arg('CJ', 2, s1), arg('CJ', 2, s2)]], rule('EF', 'EF', c('Dg', 'CJ'))).
cat_rule('Dg', s0, 1, s0, [], [s1=[arg('Dg', 1, s1)], s2=[arg('Dg', 1, s2), arg('CK', 2, s0), arg('CK', 2, s1), arg('CK', 2, s2)], s3=[arg('CK', 2, s3)]], rule('EG', 'EG', c('Dg', 'CK'))).
cat_rule('Dg', s0, 1, s0, [], [s1=[arg('Dg', 1, s1)], s2=[arg('Dg', 1, s2), arg('CL', 2, s0), arg('CL', 2, s1), arg('CL', 2, s2)], s3=[arg('CL', 2, s3)], s4=[arg('CL', 2, s4)]], rule('EH', 'EH', c('Dg', 'CL'))).
cat_rule('Dg', s0, 1, s0, [], [s1=[arg('Dg', 1, s1)], s2=[arg('Dg', 1, s2), arg('CM', 2, s0), arg('CM', 2, s1), arg('CM', 2, s2)], s3=[arg('CM', 2, s3)]], rule('EI', 'EI', c('Dg', 'CM'))).
cat_rule('Dg', s0, 1, s0, [], [s1=[arg('Dg', 1, s1)], s2=[arg('Dg', 1, s2), arg('CN', 2, s0), arg('CN', 2, s1), arg('CN', 2, s2)], s3=[arg('CN', 2, s3)], s4=[arg('CN', 2, s4)]], rule('EJ', 'EJ', c('Dg', 'CN'))).
eps_rule(s0, [], rule('As', 'As', c)).
tok_rule(angry, s0, [], [], rule('E', 'E', c)).
tok_rule(cheap, s0, [], [], rule('E', 'E', c)).
tok_rule(clever, s0, [], [], rule('E', 'E', c)).
tok_rule(gentle, s0, [], [], rule('E', 'E', c)).
tok_rule(honest, s0, [], [], rule('E', 'E', c)).
tok_rule(ill, s0, [], [], rule('E', 'E', c)).
tok_rule(important, s0, [], [], rule('E', 'E', c)).
tok_rule(interesting, s0, [], [], rule('E', 'E', c)).
tok_rule(kind, s0, [], [], rule('E', 'E', c)).
tok_rule(late, s0, [], [], rule('E', 'E', c)).
tok_rule(long, s0, [], [], rule('E', 'E', c)).
tok_rule(lost, s0, [], [], rule('E', 'E', c)).
tok_rule(old, s0, [], [], rule('E', 'E', c)).
tok_rule(poor, s0, [], [], rule('E', 'E', c)).
tok_rule(pretty, s0, [], [], rule('E', 'E', c)).
tok_rule(proud, s0, [], [], rule('E', 'E', c)).
tok_rule(right, s0, [], [], rule('E', 'E', c)).
tok_rule(sad, s0, [], [], rule('E', 'E', c)).
tok_rule(strange, s0, [], [], rule('E', 'E', c)).
tok_rule(young, s0, [], [], rule('E', 'E', c)).
tok_rule('Ann', s0, [], [], rule('D', 'D', c)).
tok_rule('Chris', s0, [], [], rule('D', 'D', c)).
tok_rule('Clare', s0, [], [], rule('D', 'D', c)).
tok_rule('David', s0, [], [], rule('D', 'D', c)).
tok_rule('Dick', s0, [], [], rule('D', 'D', c)).
tok_rule('I', s0, [], [], rule('D', 'D', c)).
tok_rule('Jenny', s0, [], [], rule('D', 'D', c)).
tok_rule('Jim', s0, [], [], rule('D', 'D', c)).
tok_rule('Joe', s0, [], [], rule('D', 'D', c)).
tok_rule('John', s0, [], [], rule('D', 'D', c)).
tok_rule('Mary', s0, [], [], rule('D', 'D', c)).
tok_rule('Pat', s0, [], [], rule('D', 'D', c)).
tok_rule('Patrick', s0, [], [], rule('D', 'D', c)).
tok_rule('Paul', s0, [], [], rule('D', 'D', c)).
tok_rule('Penny', s0, [], [], rule('D', 'D', c)).
tok_rule('Sally', s0, [], [], rule('D', 'D', c)).
tok_rule('Stephen', s0, [], [], rule('D', 'D', c)).
tok_rule('Sue', s0, [], [], rule('D', 'D', c)).
tok_rule(apples, s0, [], [], rule('D', 'D', c)).
tok_rule(eggs, s0, [], [], rule('D', 'D', c)).
tok_rule(he, s0, [], [], rule('D', 'D', c)).
tok_rule(it, s0, [], [], rule('D', 'D', c)).
tok_rule(lies, s0, [], [], rule('D', 'D', c)).
tok_rule(reading, s0, [], [], rule('D', 'D', c)).
tok_rule(they, s0, [], [], rule('D', 'D', c)).
tok_rule(us, s0, [], [], rule('D', 'D', c)).
tok_rule(always, s0, [], [], rule('U', 'U', c)).
tok_rule(so, s0, [], [], rule('U', 'U', c)).
tok_rule(too, s0, [], [], rule('U', 'U', c)).
tok_rule(very, s0, [], [], rule('U', 'U', c)).
tok_rule(accident, s0, [], [], rule('B', 'B', c)).
tok_rule(answer, s0, [], [], rule('B', 'B', c)).
tok_rule(apple, s0, [], [], rule('B', 'B', c)).
tok_rule(bill, s0, [], [], rule('B', 'B', c)).
tok_rule(book, s0, [], [], rule('B', 'B', c)).
tok_rule(box, s0, [], [], rule('B', 'B', c)).
tok_rule(boy, s0, [], [], rule('B', 'B', c)).
tok_rule(brother, s0, [], [], rule('B', 'B', c)).
tok_rule(cake, s0, [], [], rule('B', 'B', c)).
tok_rule(car, s0, [], [], rule('B', 'B', c)).
tok_rule(cat, s0, [], [], rule('B', 'B', c)).
tok_rule(clothe, s0, [], [], rule('B', 'B', c)).
tok_rule(dog, s0, [], [], rule('B', 'B', c)).
tok_rule(father, s0, [], [], rule('B', 'B', c)).
tok_rule(food, s0, [], [], rule('B', 'B', c)).
tok_rule(friend, s0, [], [], rule('B', 'B', c)).
tok_rule(girl, s0, [], [], rule('B', 'B', c)).
tok_rule(house, s0, [], [], rule('B', 'B', c)).
tok_rule(leg, s0, [], [], rule('B', 'B', c)).
tok_rule(letter, s0, [], [], rule('B', 'B', c)).
tok_rule(lie, s0, [], [], rule('B', 'B', c)).
tok_rule(man, s0, [], [], rule('B', 'B', c)).
tok_rule(mother, s0, [], [], rule('B', 'B', c)).
tok_rule(picture, s0, [], [], rule('B', 'B', c)).
tok_rule(present, s0, [], [], rule('B', 'B', c)).
tok_rule(sailor, s0, [], [], rule('B', 'B', c)).
tok_rule(ship, s0, [], [], rule('B', 'B', c)).
tok_rule(story, s0, [], [], rule('B', 'B', c)).
tok_rule(sweet, s0, [], [], rule('B', 'B', c)).
tok_rule(ticket, s0, [], [], rule('B', 'B', c)).
tok_rule(town, s0, [], [], rule('B', 'B', c)).
tok_rule(treat, s0, [], [], rule('B', 'B', c)).
tok_rule(trick, s0, [], [], rule('B', 'B', c)).
tok_rule(uncle, s0, [], [], rule('B', 'B', c)).
tok_rule(woman, s0, [], [], rule('B', 'B', c)).
tok_rule(accident, s0, [], [], rule('C', 'C', c)).
tok_rule(answer, s0, [], [], rule('C', 'C', c)).
tok_rule(apple, s0, [], [], rule('C', 'C', c)).
tok_rule(bill, s0, [], [], rule('C', 'C', c)).
tok_rule(book, s0, [], [], rule('C', 'C', c)).
tok_rule(box, s0, [], [], rule('C', 'C', c)).
tok_rule(boy, s0, [], [], rule('C', 'C', c)).
tok_rule(brother, s0, [], [], rule('C', 'C', c)).
tok_rule(cake, s0, [], [], rule('C', 'C', c)).
tok_rule(car, s0, [], [], rule('C', 'C', c)).
tok_rule(cat, s0, [], [], rule('C', 'C', c)).
tok_rule(clothe, s0, [], [], rule('C', 'C', c)).
tok_rule(dog, s0, [], [], rule('C', 'C', c)).
tok_rule(father, s0, [], [], rule('C', 'C', c)).
tok_rule(food, s0, [], [], rule('C', 'C', c)).
tok_rule(friend, s0, [], [], rule('C', 'C', c)).
tok_rule(girl, s0, [], [], rule('C', 'C', c)).
tok_rule(house, s0, [], [], rule('C', 'C', c)).
tok_rule(leg, s0, [], [], rule('C', 'C', c)).
tok_rule(letter, s0, [], [], rule('C', 'C', c)).
tok_rule(lie, s0, [], [], rule('C', 'C', c)).
tok_rule(man, s0, [], [], rule('C', 'C', c)).
tok_rule(mother, s0, [], [], rule('C', 'C', c)).
tok_rule(picture, s0, [], [], rule('C', 'C', c)).
tok_rule(present, s0, [], [], rule('C', 'C', c)).
tok_rule(sailor, s0, [], [], rule('C', 'C', c)).
tok_rule(ship, s0, [], [], rule('C', 'C', c)).
tok_rule(story, s0, [], [], rule('C', 'C', c)).
tok_rule(sweet, s0, [], [], rule('C', 'C', c)).
tok_rule(ticket, s0, [], [], rule('C', 'C', c)).
tok_rule(town, s0, [], [], rule('C', 'C', c)).
tok_rule(treat, s0, [], [], rule('C', 'C', c)).
tok_rule(trick, s0, [], [], rule('C', 'C', c)).
tok_rule(uncle, s0, [], [], rule('C', 'C', c)).
tok_rule(woman, s0, [], [], rule('C', 'C', c)).
tok_rule(today, s0, [], [], rule('AC', 'AC', c)).
tok_rule(yesterday, s0, [], [], rule('AC', 'AC', c)).
tok_rule(matter, s0, [], [], rule(d, d, c)).
tok_rule(rule, s0, [], [], rule(d, d, c)).
tok_rule(wait, s0, [], [], rule(d, d, c)).
tok_rule(come, s0, [], [], rule('Au', 'Au', c)).
eps_rule(s0, [], rule('Av', 'Av', c)).
tok_rule(will, s0, [], [], rule('Aw', 'Aw', c)).
tok_rule(have, s0, [], [], rule('Ax', 'Ax', c)).
tok_rule(fact, s0, [], [], rule('Ay', 'Ay', c)).
tok_rule(forget, s0, [], [], rule(e, e, c)).
tok_rule(know, s0, [], [], rule(e, e, c)).
tok_rule(remember, s0, [], [], rule(e, e, c)).
tok_rule(will, s0, [], [], rule('Az', 'Az', c)).
tok_rule(a, s0, [], [], rule('V', 'V', c)).
tok_rule(my, s0, [], [], rule('V', 'V', c)).
tok_rule(one, s0, [], [], rule('V', 'V', c)).
tok_rule(the, s0, [], [], rule('V', 'V', c)).
tok_rule(which, s0, [], [], rule('AD', 'AD', c)).
tok_rule(who, s0, [], [], rule('AD', 'AD', c)).
tok_rule(s, s0, [], [], rule('BA', 'BA', c)).
tok_rule(be, s0, [], [], rule('BB', 'BB', c)).
tok_rule(the, s0, [], [], rule('BC', 'BC', c)).
tok_rule(for, s0, [], [], rule('BD', 'BD', c)).
tok_rule(to, s0, [], [], rule('BE', 'BE', c)).
tok_rule(bring, s0, [], [], rule('F', 'F', c)).
tok_rule(buy, s0, [], [], rule('F', 'F', c)).
tok_rule(get, s0, [], [], rule('F', 'F', c)).
tok_rule(hate, s0, [], [], rule('F', 'F', c)).
tok_rule(have, s0, [], [], rule('F', 'F', c)).
tok_rule(leave, s0, [], [], rule('F', 'F', c)).
tok_rule(like, s0, [], [], rule('F', 'F', c)).
tok_rule(love, s0, [], [], rule('F', 'F', c)).
tok_rule(pay, s0, [], [], rule('F', 'F', c)).
tok_rule(sell, s0, [], [], rule('F', 'F', c)).
tok_rule(send, s0, [], [], rule('F', 'F', c)).
tok_rule(surprise, s0, [], [], rule('F', 'F', c)).
tok_rule(take, s0, [], [], rule('F', 'F', c)).
tok_rule(tell, s0, [], [], rule('F', 'F', c)).
tok_rule(write, s0, [], [], rule('F', 'F', c)).
eps_rule(s0, [], rule('BF', 'BF', c)).
tok_rule(will, s0, [], [], rule('BG', 'BG', c)).
tok_rule(doesnt, s0, [], [], rule('BH', 'BH', c)).
eps_rule(s0, [], rule('BI', 'BI', c)).
tok_rule(pay, s0, [], [], rule('BJ', 'BJ', c)).
tok_rule(explain, s0, [], [], rule('G', 'G', c)).
tok_rule(give, s0, [], [], rule('G', 'G', c)).
tok_rule(sell, s0, [], [], rule('G', 'G', c)).
tok_rule(show, s0, [], [], rule('G', 'G', c)).
tok_rule(teach, s0, [], [], rule('G', 'G', c)).
tok_rule(tell, s0, [], [], rule('G', 'G', c)).
tok_rule(that, s0, [], [], rule('BK', 'BK', c)).
eps_rule(s0, [], rule('BL', 'BL', c)).
eps_rule(s0, [], rule('BM', 'BM', c)).
tok_rule(have, s0, [], [], rule('BN', 'BN', c)).
tok_rule(be, s0, [], [], rule('BO', 'BO', c)).
tok_rule(been, s0, [], [], rule('BP', 'BP', c)).
tok_rule('-s', s0, [], [], rule('BQ', 'BQ', c)).
eps_rule(s0, [], rule(f, f, c)).
tok_rule('-ed', s0, [], [], rule(f, f, c)).
tok_rule('-s', s0, [], [], rule(f, f, c)).
eps_rule(s0, [], rule(g, g, c)).
tok_rule('-ed', s0, [], [], rule(g, g, c)).
tok_rule('-s', s0, [], [], rule(g, g, c)).
eps_rule(s0, [], rule(h, h, c)).
tok_rule('-ed', s0, [], [], rule(h, h, c)).
tok_rule('-s', s0, [], [], rule(h, h, c)).
eps_rule(s0, [], rule('BR', 'BR', c)).
eps_rule(s0, [], rule('BT', 'BT', c)).
eps_rule(s0, [], rule(i, i, c)).
tok_rule('-ed', s0, [], [], rule(i, i, c)).
tok_rule('-s', s0, [], [], rule(i, i, c)).
eps_rule(s0, [], rule('BU', 'BU', c)).
tok_rule('-en', s0, [], [], rule('BV', 'BV', c)).
tok_rule('-ing', s0, [], [], rule('BW', 'BW', c)).
cat_rule('At', s0, 2, s0, [], [s1=[arg('E', 1, s0)], s2=[arg('At', 2, s1)]], rule('AE', 'AE', c('E', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('D', 1, s0)], s2=[arg('At', 2, s1)]], rule(t, t, c('D', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('U', 1, s0)], s2=[arg('At', 2, s1)]], rule('CA', 'CA', c('U', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('B', 1, s0)], s2=[arg('At', 2, s1)]], rule('W', 'W', c('B', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('C', 1, s0)], s2=[arg('At', 2, s1)]], rule('Ag', 'Ag', c('C', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('AC', 1, s0)], s2=[arg('At', 2, s1)]], rule('CR', 'CR', c('AC', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg(d, 1, s0)], s2=[arg('At', 2, s1)]], rule('H', 'H', c(d, 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('Au', 1, s0)], s2=[arg('At', 2, s1)]], rule('Cw', 'Cw', c('Au', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('Av', 1, s0)], s2=[arg('At', 2, s1)]], rule('Cx', 'Cx', c('Av', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('Aw', 1, s0)], s2=[arg('At', 2, s1)]], rule('Cy', 'Cy', c('Aw', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('Ax', 1, s0)], s2=[arg('At', 2, s1)]], rule('Cz', 'Cz', c('Ax', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('Ay', 1, s0)], s2=[arg('At', 2, s1)]], rule('DA', 'DA', c('Ay', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg(e, 1, s0)], s2=[arg('At', 2, s1)]], rule('DB', 'DB', c(e, 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('Az', 1, s0)], s2=[arg('At', 2, s1)]], rule('DC', 'DC', c('Az', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('V', 1, s0)], s2=[arg('At', 2, s1)]], rule('DD', 'DD', c('V', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('AD', 1, s0)], s2=[arg('At', 2, s1)]], rule('DE', 'DE', c('AD', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BA', 1, s0)], s2=[arg('At', 2, s1)]], rule('DF', 'DF', c('BA', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BB', 1, s0)], s2=[arg('At', 2, s1)]], rule('DG', 'DG', c('BB', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BC', 1, s0)], s2=[arg('At', 2, s1)]], rule('DH', 'DH', c('BC', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BD', 1, s0)], s2=[arg('At', 2, s1)]], rule('DY', 'DY', c('BD', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BE', 1, s0)], s2=[arg('At', 2, s1)]], rule('DZ', 'DZ', c('BE', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('F', 1, s0)], s2=[arg('At', 2, s1)]], rule('Da', 'Da', c('F', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BF', 1, s0)], s2=[arg('At', 2, s1)]], rule('Db', 'Db', c('BF', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BG', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dc', 'Dc', c('BG', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BH', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dd', 'Dd', c('BH', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BI', 1, s0)], s2=[arg('At', 2, s1)]], rule('De', 'De', c('BI', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BJ', 1, s0)], s2=[arg('At', 2, s1)]], rule('Df', 'Df', c('BJ', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('G', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dg', 'Dg', c('G', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BK', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dh', 'Dh', c('BK', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BL', 1, s0)], s2=[arg('At', 2, s1)]], rule('Di', 'Di', c('BL', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BM', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dj', 'Dj', c('BM', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BN', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dk', 'Dk', c('BN', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BO', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dl', 'Dl', c('BO', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BP', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dm', 'Dm', c('BP', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BQ', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dn', 'Dn', c('BQ', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg(f, 1, s0)], s2=[arg('At', 2, s1)]], rule('Do', 'Do', c(f, 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg(g, 1, s0)], s2=[arg('At', 2, s1)]], rule('Dp', 'Dp', c(g, 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg(h, 1, s0)], s2=[arg('At', 2, s1)]], rule('Dq', 'Dq', c(h, 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BR', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dr', 'Dr', c('BR', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BT', 1, s0)], s2=[arg('At', 2, s1)]], rule('Ds', 'Ds', c('BT', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg(i, 1, s0)], s2=[arg('At', 2, s1)]], rule('Dt', 'Dt', c(i, 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BU', 1, s0)], s2=[arg('At', 2, s1)]], rule('Du', 'Du', c('BU', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BV', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dv', 'Dv', c('BV', 'At'))).
cat_rule('At', s0, 2, s0, [], [s1=[arg('BW', 1, s0)], s2=[arg('At', 2, s1)]], rule('Dw', 'Dw', c('BW', 'At'))).
